### ISSUE TITLE
Define steps to customize distro

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix#1]
Document files and folders to customize browsers
- [ ] start page
- [ ] search engines
- [ ] amazon search

Document how to customize desktop
- [ ] background
- [ ] sound

Meta Package
- [x] Propose, build and document how to build a meta-package, that changes the distro accordingly.

References:
- https://code.launchpad.net/~lubuntu-dev/lxde/
- https://code.launchpad.net/~lubuntu-desktop/+junk/lubuntu-tools

**Comment by Abhi2424shek** [comment]
Can we use the wiki pages on the repo?

**Comment by mariobehling** [comment]
Please add the info in the Readme.md. We will at one point create a dev page from the Readme files. As we progress we can also use the docs folder for more detailed info. For now the Readme.md is good. We want to avoid dependencies on additional repos and Github wikis.

**Comment by abishekvashok** [comment]
Can we have updates here?
