### ISSUE TITLE
Firefox permission problem due to conflicting package

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#100]
Firefox is not starting up due to conflicting package in meilix-default-setting
![screenshot_firefox_2017-07-22_03 08 49](https://user-images.githubusercontent.com/15213246/28483493-2d439f30-6e8b-11e7-8e46-de245bb85f0b.png)

**Comment by tabesin** [comment]
Why does firefox get installed after customized settings from meilix-default-settings?

**Comment by meets2tarun** [comment]
> Why does firefox get installed

Firefox is included in the metapackage, it is independent of the settings in the meilix-default-settings.

**Comment by tabesin** [comment]
Why is Firefox then installed after the meilix-default-settings package?

**Comment by meets2tarun** [comment]
Starting to illustrate our process from the very beginning:
First of all, we tried to run the Firefox through the panel options, which doesn't show any message at all.
Second, we tried to open it through the terminal which shows that `permission denied`.
Then we remove the firefox and install it again and now you can follow the screenshot.

**Comment by abishekvashok** [comment]
@meets2tarun remove that package off from meilix-default-settings and repack the metapackage.
