### ISSUE TITLE
Icons are not showing 

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#101]
No icons are showing up in meilix iso neither in files nor in folders

**Comment by xeon-zolt** [comment]
pcmanfm too

**Comment by meets2tarun** [comment]
Can we try nemo ?

**Comment by xeon-zolt** [comment]
https://wiki.archlinux.org/index.php/PCManFM#No_icons
we can try this

**Comment by tabesin** [comment]
In terms of process, it is easier to process when to have single issue tickets like "install oxygen icons". "install dropbox" "install vlc" and so forth. Instead of additional tasklists you simply convert the tasklist items into issues that are small enough to be solved in a single day or less.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/pull/97/files#diff-0b83f9dedf40d7356e5ca147a077acb4R150
This line installs the icon but in the meilix iso this actually doesn't get install.

**Comment by meets2tarun** [comment]
The issue is solved in the iso latest release:
https://github.com/fossasia/meilix/releases/tag/untagged-481c53d0a391cff65a58

**Comment by tabesin** [comment]
Anyway, please take the "complete" package for the oxygen icons
