### ISSUE TITLE
Missing hotelos folder

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#104]
Hostname, as well as the username of the meilix, is hotelos. 
`hotelos@hoteslos:~$` proves the above.
But the issue is that we didn't get hotelos folder inside the home folder while `unsquash` it using `sudo unsquashfs -n mnt/casper/filesystem.squashfs`

**Comment by tabesin** [comment]
" we didn't get hotelos folder inside the home folder "

Please explain what you mean. It is very difficult to grasp from the description.

unsquashfs is readonly.

**Comment by meets2tarun** [comment]
Issue is:
By using command `unsquashfs -n mnt/casper/filesystem.squashfs`, we unsquash the file system and will try to make changes inside it (we get distro file system inside) then repack it into the iso. It's like customizing the iso. 
But the issue is that the file system doesn't contain the hotelos (user folder) inside its home folder.

**Comment by xeon-zolt** [comment]
we are going to edit inirtd file for that as the liveuser is created during
boot

**Comment by tabesin** [comment]
Apparently the user does not exist yet. So why don't you take /etc/skel/ for all of this? http://www.linfo.org/etc_skel.html

**Comment by meets2tarun** [comment]
@tabesin we are working on the very same strategy.

**Comment by abishekvashok** [comment]
Was this fixed

**Comment by meets2tarun** [comment]
@abishekvashok 
Almost, we changed the strategy to work on the issue and the reason for the opening of the issue has been resolved. 
The question was to get the files in the home folder of the user and we are successful in doing that.
