### ISSUE TITLE
Travis CI is failing

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/meilix#11]
Here's the problem: 
![image](https://cloud.githubusercontent.com/assets/8947010/21478731/28b22adc-cb74-11e6-8a3b-6fbb15f2a218.png)

As you can see at line no 2479-2482 there are some errors namely:
```
Errors were encountered while processing:
 libpam-systemd:i386
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**As you can see there was an error in processing the `libpam` package which belonged to `systemd`.**

_Note: PAM = Pluggable Authentication Modules. Basically, it is a flexible mechanism for authenticating users and we can't omit it so please deliver a fix._

@mariobehling since we lack contributors can we create a task for this?

**Comment by yukiisbored** [comment]
It's because Travis is running a distro that doesn't have systemd. Let me try running it on a Xenial docker container

**Comment by yukiisbored** [comment]
Migrating `upstart` to `systemd` is impossible without doing a release upgrade (NO, Don't do this inside Travis' container)

**Comment by Abhi2424shek** [comment]
We can safe escape that portion

**Comment by yukiisbored** [comment]
Anyway, I'm doing this issue as we speak. Can I get assigned for this issue?

**Comment by Abhi2424shek** [comment]
Or @yukiisbored make an alternative patch for liban it can't be avoided for security.

**Comment by yukiisbored** [comment]
@Abhi2424shek Workarounds are great, but they shouldn't be used on production. We can just use Docker for this ;)

**Comment by yukiisbored** [comment]
I'm avoiding the usage of Vagrant/VMs because it's a heavy load for Travis

**Comment by Abhi2424shek** [comment]
But more than docker they are quick however feel free to make a PR with docker and let us see how it works

**Comment by yukiisbored** [comment]
Whoops, I dun goofed. I didn't see it actually sets the release version on `debootstrap`

**Comment by Abhi2424shek** [comment]
@yukiisbored please understand the code then code! Good luck 👍

**Comment by yukiisbored** [comment]
@Abhi2424shek Heh, I'm still fixing it. Just have to properly unmount the pseudo-filesystems before it builds the image
