### ISSUE TITLE
Debrand startup screen

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#116]
- Issue type: Feature request 

### Short description

Technically Meilix is a Ubuntu derivate. When you boot up Meilix it says Ubuntu 17.04 in the load screen. You can disable that startup screen or debrand it or replace it by sth else as it confuses our users.

### Steps to reproduce

1. Generate ISO
2. Boot up Meilix 
3. Loading notice says Ubuntu 17.04

### Expected behaviour

A startup screen - if any - says meilix loading up or even "LinuxFriends Event Distribution"(or whatever the user wanted) loading but not Ubuntu 17.04

### Actual behaviour

You get informed that Ubuntu 17.04 is loading, together with the . . . . progress display.

### Hints

Look at Plymouth configuration and theming.

**Comment by meets2tarun** [comment]
This issue still persists.

**Comment by tabesin** [comment]
I suggest to follow the https://github.com/fossasia/meilix/issues/158 approach and merge what we did so far into this. That is take the most recent ubuntu theming packages as a base. Our current approach is based on 4 year old incarnations.

**Comment by abishekvashok** [comment]
Is this one solved?
