### ISSUE TITLE
Chrome not found in meilix

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#117]
- Issue type: Bug report 

### Short description
Google Chrome browser is not found in the iso

### Expected behaviour

https://github.com/fossasia/meilix/pull/97/files#diff-0b83f9dedf40d7356e5ca147a077acb4R134
This line installs the chrome browser, so it is expected that the browser should be there.

### Actual behaviour

But the browser isn't there.

**Comment by tabesin** [comment]
Try:
1) -y parameters
2) add repo to our sources list instead of monkey patching

**Comment by tabesin** [comment]
https://github.com/fossasia/meilix/pull/97/files#diff-0b83f9dedf40d7356e5ca147a077acb4R134

**Comment by tabesin** [comment]
Also move key adding to the key section of the script.

**Comment by tabesin** [comment]
Please also ensure that you install a i386 build when the build is i386.

**Comment by meets2tarun** [comment]
I too saw that chorme for 32 bit is not longet there
What should we do now?

**Comment by xeon-zolt** [comment]
why do we need to use google chrome when chromium is present?

**Comment by tabesin** [comment]
Anyway, add the repo to the sources.list and the key to the add-key section of build.sh

If you take stable it should still be available in 32bit

**Comment by meets2tarun** [comment]
> why do we need to use google chrome when chromium is present?

https://github.com/fossasia/labs.fossasia.org/issues/135

**Comment by tabesin** [comment]
So I tried it manually on a hotelos image: 
![hotelosd](https://user-images.githubusercontent.com/10114907/28754003-09e0d8ba-753d-11e7-93cb-aef6390fb4bd.png)

**Comment by tabesin** [comment]
I would suggest there is nothing to do. Otherwise, if a decision is made to include the package anyway, we can download an older Chrome 32Bit Ubuntu version to the repo and install the deb manually but that would not be recommended (aka slavish support of 135 list).

**Comment by abishekvashok** [comment]
> we can download an older Chrome 32Bit Ubuntu version to the repo and install the deb manually but that would not be recommended (aka slavish support of 135 list).

Well that would be hard, we would be falling back on security and other things.

**Comment by meets2tarun** [comment]
IMO, discard the idea to include chrome

**Comment by abishekvashok** [comment]
> IMO, discard the idea to include chrome

Yes, why should we include chrome and chromium. CC: @mariobehling
