### ISSUE TITLE
Notice of 12.04 cdrom repository has no release file

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#119]
- Issue type: Bug report

### Short description

Problem with the "cdrom" file source. A issue emerges with the cdrom repo (which afaik is a dummy repository added by build.sh). Try apt update on a generated ISO live system.

![test](https://user-images.githubusercontent.com/10114907/28754037-a575883e-753d-11e7-95b8-db83a3e4b43f.png)

**Comment by tabesin** [comment]
Quantal seems to stem from the casper environment.

**Comment by xeon-zolt** [comment]
I am creating a script for that instead of uploading the modified initrd

**Comment by tabesin** [comment]
I talked to Mario yesterday. He prefers an install option.

**Comment by abishekvashok** [comment]
We should include a release file then or remove packages from the cdrom i.e, the live system which isn't nice.
