### ISSUE TITLE
Disable About LXQT label in menu

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#121]
- Issue type: Feature request 

### Short description
Disable the display of the about-lxqt entry in the menu.
(on a user system this could be done via "menulibre"; then find out what it does)

![fossasiatheme](https://user-images.githubusercontent.com/10114907/28756873-5741a7ee-7577-11e7-8b5f-257b4ed8b263.png)

**Comment by abishekvashok** [comment]
I think there's a config file that can be pasted at the HOME directory to disable that. But, why should we remove that really?

**Comment by tabesin** [comment]
It is a junior job item of polishing the generated distribution. It is super-easy to do and a simple task to recruit new developers or showcase how to hack Meilix for fun.

I think LXQT does not add to user experience at this place and Meilix users should not have to worry or think about what LXDE might be, in this prominent place the item is clearly misplaced, so any distribution package would change that.

**Comment by tabesin** [comment]
/usr/share/applications/lxqt-about.desktop

NoDisplay=true
[Desktop Entry]

bzw. ~/.local/usr/share

**Comment by tabesin** [comment]
Current implementation affected by https://github.com/fossasia/meilix/issues/183

**Comment by vaibhavsingh97** [comment]
@tabesin Can i take up this issue?

**Comment by tabesin** [comment]
Please try it out.

Technically it should already be fixed but... apparently the skel trick does not work for deeper directory structures.

**Comment by tabesin** [comment]
Should be resolved in meilix-default-settings... ?!

**Comment by pranav1698** [comment]
I was just working on it and it is resolved by inserting the no-display line in the file you mentioned earlier in the conversation

**Comment by tabesin** [comment]
Right. It assumes it existence. However it is more general.

Am Sa., 24. Nov. 2018, 20:27 hat Pranav Kulshrestha <
notifications@github.com> geschrieben:
