### ISSUE TITLE
Better Deployment for Meilix Generator

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#122]
Currently, we are deploying on Github only due to which we have a collection of many builds and the pile keep on increasing and requires a cleaning from time to time so to avoid that we can shift from GitHub deployment to [transfer.sh](https://transfer.sh/) where we can host the build for 14days and that can be used for the time period of the event also for which the build is required

**Comment by tabesin** [comment]
I would strongly advise in the current phase to focus to much on the environment. In principle there is no point to store the generated content longterm or midterm at this stage on our side. A user generates an ISO and uploads it him- or herself to any file sharing service that suits him. At the present state the generated content is mostly beta state, so a clear priority is to get it into a better working state.

**Comment by tabesin** [comment]
My 2cents:
Setting each time a meilix-latest.iso symlink to the latest build.
Plus automatically deleting all isofiles older than x days

**Comment by meets2tarun** [comment]
> Setting each time a meilix-latest.iso symlink to the latest build.
> Plus automatically deleting all isofiles older than x days

How can such be achieved, I saw the way to delete all the releases at a time using Github API but not at any specific days.

**Comment by abishekvashok** [comment]
> How can such be achieved, I saw the way to delete all the releases at a time using Github API but not at any specific days?

Use cron jobs provided by travis to do so, maybe everyday or so, if you want I would provide you a script.

**Comment by meets2tarun** [comment]
Sure @abishekvashok

**Comment by abishekvashok** [comment]
@meets2tarun link me to that api documentation

**Comment by meets2tarun** [comment]
https://developer.github.com/v3/repos/releases/

**Comment by abishekvashok** [comment]
```
#!/usr/bin/env bash
set -e

response=`curl https://api.github.com/repos/fossasia/meilix/releases | jq '.[] | .id, .published_at'`

index=1
delete=0
current_year=`date +%Y`
current_month=`date +%m`
current_day=`date +%d`

for i in $response; do
    if [ $((index % 2)) -eq 0 ]; then
        published_year=${i:1:4}
        published_month=${i:6:2}
        published_day=${i:9:2}

        if [ $published_year -lt $current_year ]; then
             let "delete=1"
        else
            if [ $published_month -lt $current_month ]; then
                let "delete=1"
            else
                if [$((current_day-$published_day)) -gt 10 ]; then
                    let "delete=1"
                fi
            fi
        fi
    else
        if [$delete -eq 1]; then
            curl -X DELETE -H 'Authorization: token XXXXXXXXX' https://api.github.com/repos/fossasia/meilix/releases/$i
            let "delete=0"
        fi
    fi
    let "index+=1"
done

```

**Comment by meets2tarun** [comment]
> Do you want a PR?

Sure

**Comment by abishekvashok** [comment]
oh sorry @meets2tarun we would need an access token, I don't have access  so please use this script with your access token and make a PR

**Comment by tabesin** [comment]
BTW, this works: https://github.com/fossasia/meilix/releases/latest

**Comment by abishekvashok** [comment]
@tabesin that does'not clean the releases, it just fetches the latest release, as of now, we want to clean the releases which are no longer required and will be much more spammy when in production.

**Comment by meets2tarun** [comment]
> we would need an access token, I don't have access so please use this script with your access token and make a PR

Give a PR with your token, then I'll edit it with mine.
