### ISSUE TITLE
Reduce the size of the output .iso

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#123]
- Issue type: Feature request 

### Short description

Lubuntu takes less than ! GB to download while ubuntu takes a mere 5000mb, it would be better if we could reduce size of the output iso.

**Comment by xeon-zolt** [comment]
we can use better compression for squashing but that will cost time and may not give required compression

**Comment by abishekvashok** [comment]
> we can use better compression for squashing but that will cost time and may not give required compression

We would need try everything to make sure everything we have is at it's maximum.

**Comment by tabesin** [comment]
Your main argument is download time. For me it takes 35 minutes. I'd suggest to keep the status quo, for a final version we may well end up with a 3GB image and that would be fine. Download time, build time, we don't have to optimize that while the ISO itself is in beta stage.
