### ISSUE TITLE
Multiple keyboard layouts support

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#124]
- Issue type: Bug report/Feature request 

### Short description
install local language keyboard layouts
- might be a user configuration
- There are a limited number of keyboards, same like with packages
- all keyboards are preinstalled
- there is a menu somewhere which may only appear if you as a user can choose between several languages. There, these languages should appear

### Usecase

I am a German citizens and my keyboard uses a different layout. Right now Meilix defaults to US keyboard, so I have to recall their layout.

### Description
(copied and pasted from the hangout 7 protocols, feel free to add clarity)

**Comment by abishekvashok** [comment]
> install local language keyboard layouts

We should ask this in the generator and add that only layout.

**Comment by meets2tarun** [comment]
And how do we do that `that ask the user and install its keyboard` ?

**Comment by abishekvashok** [comment]
> And how do we do that that ask the user and install its keyboard ?

Just as we did for the wallpaper. Install the locales on demand in the generator branch.

**Comment by abishekvashok** [comment]
@tabesin was this solved?
