### ISSUE TITLE
gh-pages branch configuration is changed

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#125]
- Issue type: Bug report 

### Short description

We provided a ppa in the gh-pages branch but however someone changed the settings. https://meilix.fossasia.org doesnot point to it.

**Comment by tabesin** [comment]
Does https://github.com/fossasia/meilix/blob/master/scripts/aptRepoUpdater.sh not work any more? Any useful failure notices?

Or is is just the meilix.fossasia.org website is not pointing to the gh pages ppa anymore?

**Comment by abishekvashok** [comment]
> Does https://github.com/fossasia/meilix/blob/master/scripts/aptRepoUpdater.sh not work any more? Any useful failure notices?

It works but before that build errors.

**Comment by abishekvashok** [comment]
And the bot has been pushed off rights @mariobehling pls enable it again as done in the past to make it work. The username is `apt-bot`, let me know when you did so.

**Comment by tabesin** [comment]
If you need something from Mario that no other person could fix, feel free to add him as Assignee (as I just did). 

We also have to ensure to make our issue report as precise as possible and add all the data needed. E.g. I have no idea if Mario knows exactly how to "enable it again" as he might have disabled them by some other routine action. A "someone changed the settings" is not all too helpful as it requires context.

**Comment by abishekvashok** [comment]
> We also have to ensure to make our issue report as precise as possible and add all the data needed. E.g. I have no idea if Mario knows exactly how to "enable it again" as he might have disabled them by some other routine action. A "someone changed the settings" is not all too helpful as it requires context.

He's he co-founder of FOSSASIA and he really knows how to do it.

>  feel free to add him as Assignee (as I just did).

Assignees can be asigned olny by people with access I guess, my access was revoked in the not so old past.

**Comment by abishekvashok** [comment]
@mariobehling will we need the PPA? if yes, please enable it.

**Comment by mariobehling** [comment]
@abishekvashok The bot has not been disabled. There must be another reason. Or does it mean admin rights? What about alternative ways, what options are there?

![screenshot from 2017-08-27 14-31-33](https://user-images.githubusercontent.com/1583873/29749791-97f2d5c4-8b34-11e7-9aad-4da8d956191a.png)

**Comment by abishekvashok** [comment]
@mariobehling sorry if were not clear. The problem is that,
currently `https://meilix.fossasia.org` does'not point to the gh-pages branch of this site.

> Or does it mean admin rights?

No.

>  What about alternative ways, what options are there?

Go to the deployment group in the settings and fix it up. I don't have write access, I thought you knew to do so. Don't you?

**Comment by meets2tarun** [comment]
> Go to the deployment group in the settings and fix it up

Where is this deployment group can be found?
@abishekvashok

**Comment by abishekvashok** [comment]
In the settings tab, go down a bit into the repository settings.

**Comment by meets2tarun** [comment]
The issue is that http://fossasia.github.io/meilix/ doesn't redirect to https://meilix.fossasia.org

**Comment by abishekvashok** [comment]
There is an option to configure manual domain @mariobehling can you look at the config again pls?

**Comment by meets2tarun** [comment]
This is working now! 👍
