### ISSUE TITLE
Build is errored

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#126]
- Issue type: Bug report

### Short description
401 Bad credentials for deployment, please provide valid access tokens,

### Correct Logged Line
`/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)`

### Reason
The credentials provided were invalid,the access tokens or so, maybe @mariobehling could provide some access token like he did in phimpe-android.

**Comment by tabesin** [comment]
Where and how did this error emerge? Using build.sh?

**Comment by abishekvashok** [comment]
`.travis.yml`

I guess in the deploy section.

**Comment by tabesin** [comment]
See the last commit of @meets2tarun https://github.com/fossasia/meilix/commit/1d4804979b6100ca27212e0b33638ef4d912d7d0

   api_key:
-      secure: "tVVKOMh0dZCrHkAfoqIYJYleJwTwXptumugYVcGi/WDaeFi9o1ROTKVdLXUO2CcAUgWUphWjnckF4uVdKBcCB87Af0hgQBXdpDJ4VSb2FFjjY3Lf5dpR1FTYR6Tqsn821mYM17wtwmO1tlg8zFqd1yysr36wZ0EqzFwBtV2FA0jNfxGtFyyJRZnDcCQqwREc2iIENSt8tE787HbwPaWGBEkpC8zYwNYkQXPgFvTi+Z/6Tnobz7gnk9wQFuzFDymr6sDTQF+2ycfGnJnXDOZjqC5haDZbXop6dR/ru6hwO6U4khQIFHEPMZEEHnocB1gOOSiM9Z/yztmY18X4jzx8gZAMIrdKwYlZzEeVAbnlX0WXfjOFmcKIvaMtdNZg9QJil3ePPq/80uNo4TGUy+04ll6jBqqMf4BTs/dxohLyksxN79iuAplRtEl96ZQG+0VI1B0OE3WjwtcuvcuTW7oZ1sOULY4UsNmIdPpJZqIrQpN4AevRJ6DV844uvJ63Sbdzyu0EjMTp+h+2dWiQnnW4aP0mbYsBGWTj0vM2CD/fHtM9W6oVNqLsF7pEe9fg7d2hYJS7Zkuwco33WHqy4JGvLl9uyzSsy0cueJgwg5DYJ8zWDzhlCbKtEk1kG+eKVj+C5rG4shOMK4zf+0iVn5BCNB5d3OgLpAGJwFx1uqqTMrc="
+      secure: "nAvyjKgkn5G7BYXq85kNXBgb3fdzVSVibvaJKWftimjhHjKzjNfcoUk/IvuoEmwpP6TofgVRx2T689DaUqW29TVXV5O23DvOyJE6SpO7xn0yPC12SPPy3nwwCWkGYvy77akz3N+DvIwGZ712lF2gttTB/mjNB1ZcX5438nCDI1hUw5TcH2QoajhxGJVDJoHQBUxWcOLQh+N+6+ZGnenR7wfLcYOmC6dLNSS9Mn2f/IPF3y3xmq3HZ7CJpHJcfIQ1a0bnHa2h7CIMRZZeXzK/W2RD1qaZ2upz33lVgpCq+/pJCED3vk+XZgmATJML8vzRsY1FlgXgEfWYmaJlsUEcNb/Llu4hwmA9pFO0pI432S3z4pX7NlcVy8Om0eaYvMbyWX4VTOz1urutWTNHQ5337wbkaPYk5ELoI7Ph2pe0uvtlrHzCO6sQWjg79asyFj2zxefOWxRM4d8k1eRQoUZaRpq95wBVYbVCiZqMc+V7TrABBlfC7f8iDmTA4nLmH6f8RIHFL018ikgd6CaRbpSO2XSSNmktR7fuLmC68vBZ64CCxVGMn0poNbdHZVphQ3KgiKH2c2Qb990XgwV/YYDNrjgh2qwpB+NzhE3PJIYWs1AGyEU9fJRJV2ElfLeel9vAWqWSZ/7q+0yPb6ScVCQ4SOJ1TYUpb8qOV3VqgbN/BwQ="

**Shall we .gitignore .travis.yml?**

**Comment by abishekvashok** [comment]
> Shall we .gitignore .travis.yml?

Hey it's required by Travis CI to run. Travis CI runs the code as linted down in .travis.yml. We are using Travis to build to iso file. We can't do that.
