### ISSUE TITLE
Make the releases from master and generator branch distinguishable

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#127]
- Issue type: Feature request 

### Short description
Make the releases from master and generator branch distinguishable somehow will do us great benefits, it will help us in #128

**Comment by abishekvashok** [comment]
@meets2tarun @xeon-zolt can someone of you brief us on how the releases are named?

**Comment by xeon-zolt** [comment]
generator releases are named as custom-meilix under the tag name sent by webapp

**Comment by abishekvashok** [comment]
then, the master ones? @xeon-zolt

**Comment by meets2tarun** [comment]
@abishekvashok 
> then, the master ones? 

"https://github.com/fossasia/meilix/releases/download/${TRAVIS_TAG}/meilix-zesty-`date +%Y%m%d`-i386.iso"
This way the master release is named and tag is a random string and here we are assigning it through environment variable to predict a ISO link beforehand.
Source: https://github.com/fossasia/meilix-generator/blob/master/script.sh#L21

**Comment by abishekvashok** [comment]
Ok look, can we make the  $TRAVISTAG for master and generator branch distinguishable?

**Comment by xeon-zolt** [comment]
@meets2tarun that method of release for generator is changed now all the release have link like 
https://github.com/xeon-zolt/meilix/releases/download/${TRAVIS_TAG}/meilix-i386-custom.iso

@abishekvashok TRAVIS_TAG is not used for master branch releases

**Comment by abishekvashok** [comment]
@xeon-zolt @meets2tarun maybe you could make the master branch contain a word like `base` or something.

**Comment by tabesin** [comment]
What is the difference in purpose between meilix-generator and the generator branch of meilix?

**Comment by meets2tarun** [comment]
Meilix generator is the webapp uses the generator branch of meilix to build the ISO.

**Comment by abishekvashok** [comment]
I didn't get that, please punctuate correctly.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix#branch-policy
https://github.com/fossasia/meilix-generator#meilix-generator
here it is said that it uses meilix script, more precisely it uses generator branch of meilix.
verify it here: https://github.com/fossasia/meilix-generator/blob/master/travis_tokens
We'll edit this in the last week (this week).

**Comment by tabesin** [comment]
The mid term approach should be to "merge" both branches, that is get rid of generator branch. That is you have two kinds of builds processes in the master branch, first using defaults, second using custom meilix-webapp settings.

**Comment by abishekvashok** [comment]
What about build times, I guess the generator branch is taking just 5mins to make the apk as it fetches an apk already made in meilix. Maybe, we could compare changes and do the build, what do you say guys?

**Comment by tabesin** [comment]
Technically generator should not be a "branch" because a branch is a variation of the same code base.

**Comment by abishekvashok** [comment]
Then a new repo? Or should it be done in the generator branch inside heroku? But do heroku support `sudo`?

**Comment by tabesin** [comment]
My top priority is to get the master branch sanitized.

**Comment by meets2tarun** [comment]
@abishekvashok 
>But do heroku support `sudo`?

No

**Comment by xeon-zolt** [comment]
> Technically generator should not be a "branch" because a branch is a variation of the same code base.

generator branch is now totally unrelated to the master it contains the ISO download and modification scripts only for faster building process

**Comment by tabesin** [comment]
Exactly.
