### ISSUE TITLE
Make generator branch independent

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#129]
- Issue type: Feature request 

### Short description

Now generator branch is in sync with the master branch. It means it shows `This branch is 30 commits ahead, 25 commits behind the master. `

### Description

The idea is to make this independent like that of the gh-pages branch.

**Comment by meets2tarun** [comment]
@tabesin 
Can you help us regarding this?

**Comment by meets2tarun** [comment]
@tabesin  We need you to do this.

**Comment by tabesin** [comment]
The task would be to make it obsolete because master does it,
