### ISSUE TITLE
Required Contribution.md file 

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#131]
- Issue type: Feature request 

### Short description

We require a contribution.md file for the repository and this issue is made to collectively collect the ideas then one will gather all of those to design it.

**Comment by abishekvashok** [comment]
Basically we could put these small things off and let's code, that will be much better.

**Comment by meets2tarun** [comment]
Things came to my mind and I made the issues so that one can do it in the future and it also matters to follow to best practices. The issue is made to get the best opinion and learn here. This is a side job and our main concern is code but this issue will be responsible to get the best code out of the box.

**Comment by tabesin** [comment]
If it's won't fix it could be closed for now
