### ISSUE TITLE
Move the script to script folder

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#132]
- Issue type: Feature request 

### Short description

Moving the script like `debuid.sh` to the script folder.

**Comment by tabesin** [comment]
Note that debuild always has to get executed in root. Please sent a clean PR when you are done.

**Comment by invinciblycool** [comment]
Can I take this up as my first issue!
:smile:

**Comment by xeon-zolt** [comment]
go on @invinciblycool

**Comment by vaibhavsingh97** [comment]
@xeon-zolt Can i claim this issue? Since there is no responce from @invinciblycool

**Comment by meets2tarun** [comment]
@invinciblycool Are you working on the issue?
If so, please file a PR soon.

**Comment by invinciblycool** [comment]
No, I guess I need to learn a lot more before I get into meilix.
@vaibhavsingh97 go on if you want.

**Comment by meets2tarun** [comment]
@invinciblycool 
I don't think so, it's a junior job and it's too easy, there is merely no meilix related matter in this issue.
If you want to get into Meilix then try to get into its development, ask on gitter or here and learn.
I believe you can do much better. Make sure you register for codeheat [here](https://docs.google.com/forms/d/e/1FAIpQLSfhIZHnDIFwHZjRHrp1LmzcBE5eaAtudCFgQKEoFwxb229Ulw/viewform) and start contributing.

@vaibhavsingh97 Kindly register for codeheat and I'll be waiting for your PR on this issue.

Thank You
