### ISSUE TITLE
Disabling Screen Saver in meilix

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#135]
- Issue type: Feature request 

### Short description

We need to disable the screen saver in the meiix ISO

### Usecase

This feature is one of the requirement as mention https://github.com/fossasia/labs.fossasia.org/issues/135
### Description

To disable we have to edit a config file located in or where should the screen saver switch-off setting go into .xsessionrc or .xinitrc or .profile?

**Comment by tabesin** [comment]
Sent you a PR to your screen dimming repo which goes for .profile.

**Comment by meets2tarun** [comment]
This is the latest ISO and in this screen saver is working
https://github.com/fossasia/meilix/releases/tag/untagged-1cef988b4352d7160278

**Comment by meets2tarun** [comment]
@tabesin https://github.com/fossasia/meilix/pull/136 This one can't solve the issue.
