### ISSUE TITLE
Remove outdated binary Firefox in metapackage

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#137]
- Issue type: Bug report
### Short description

The Meilix-default-settings package includes several binary overwrites. Some files may be needed for the Firefox customization but not all of them.

### Environment
Selecting previously unselected package meilix-default-settings.
(Reading database ... 156344 files and directories currently installed.)
Preparing to unpack meilix-default-settings_1.0_all.deb ...
Unpacking meilix-default-settings (1.0) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/etc/apport/native-origins.d/firefox', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/applications/firefox.desktop', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/applications/chromium-browser.desktop', which is also in package chromium-browser 59.0.3071.109-0ubuntu0.17.04.1360
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/man/man1/firefox.1.gz', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/apport/package-hooks/source_firefox.py', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/initramfs-tools/scripts/casper-bottom/15autologin', which is also in package casper 1.380
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/lintian/overrides/firefox', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/doc/firefox/copyright', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/doc/firefox/changelog.Debian.gz', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/doc/firefox/MPL.gz', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/share/doc/firefox/README.Debian', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libsoftokn3.chk', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libnss3.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libnspr4.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libsmime3.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/firefox.sh', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libnssdbm3.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libnssckbi.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libplc4.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libsoftokn3.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libplds4.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/omni.ja', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libmozsqlite3.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/defaults/pref/vendor-gre.js', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/defaults/pref/channel-prefs.js', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/dependentlibs.list', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/distribution/searchplugins/locale/en-US/google.xml', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/firefox', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/platform.ini', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libnssutil3.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/plugin-container', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/application.ini', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/crashreporter.ini', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/crashreporter', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libssl3.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libnssdbm3.chk', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/firefox/libxul.so', which is also in package firefox 54.0+build3-0ubuntu0.17.04.1
Setting up meilix-default-settings (1.0) ...

**Comment by tabesin** [comment]
sudo apt-get -o Dpkg::Options::="--force-overwrite" install firefox

installs a running firefox on the system by overwriting all the metapackage stuff.

**Comment by meets2tarun** [comment]
@tabesin 
How can one reproduce this error?

**Comment by niccokunzmann** [comment]
Reproduce by installing firefox on the live iso with `sudo apt-get install firefox`.
There is a binary package in the meilix-default-settings directory: https://github.com/fossasia/meilix/search?utf8=%E2%9C%93&q=firefox&type=
