### ISSUE TITLE
Any PR doesn't get automatically debuild

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#138]
- Issue type: Bug report

### Short description

Although we've implemented the script for debuild.sh but its actually not debuild the PR from its own end.

**Comment by tabesin** [comment]
According to my research and the logs it is build (what currently fails is ISO deployment for permissions reasons). Because Travis build servers mirrors the github repository you won't see any build meta packages within the repo. I added a missing package that was needed for debuild to function.

**Comment by tabesin** [comment]
Side question: Why don't we put the metapackage in a repository of its own and build it?

**Comment by tabesin** [comment]
https://travis-ci.org/fossasia/meilix/requests

**Comment by tabesin** [comment]
The first failed build is Fixes the conflicting package for Firefox present i

**Comment by tabesin** [comment]
You changed the Travis API key, may that have caused the issue?
https://github.com/fossasia/meilix/commit/035f12650a0984f17007182e60262954c9dd9a77#diff-354f30a63fb0907d4ad57269548329e3

**Comment by meets2tarun** [comment]
But the issue is different that is of debuilding the PR to avoid for us to resolve the conflicts as this PR has https://github.com/fossasia/meilix/pull/110

**Comment by meets2tarun** [comment]
> Side question: Why don't we put the metapackage in a repository of its own and build it?

We can but that may increase meilix source code size.

**Comment by tabesin** [comment]
build triggers debuild in travis

**Comment by meets2tarun** [comment]
then why conflicts get arise always?

**Comment by meets2tarun** [comment]
No need to build PR
Kindly go through this comment
https://github.com/fossasia/meilix/pull/136#issuecomment-320295778
and the debuild.sh will do the rest of the job for us.
Thank You
