### ISSUE TITLE
Only live boot is available in the ISO

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#144]
- Issue type: Bug report 

### Short description

The ISO has two options:
- live boot 
- install the system

But both the ways start the live system even the install system also

**Comment by abishekvashok** [comment]
Do we have a installer here? I don't think so.

**Comment by xeon-zolt** [comment]
ubiquity is missing

**Comment by tabesin** [comment]
Let's get it back then.

I guess Marios request to remove the installer was misunderstood, he meant: remove the Install entry from being displayed at the live cd desktop.

**Comment by meets2tarun** [comment]
So it means that we will give the user only live boot option in the ISO? @tabesin

**Comment by abishekvashok** [comment]
@meets2tarun I guess no.

> he meant: remove the Install entry from being displayed at the live cd desktop.

**Comment by meets2tarun** [comment]
@abishekvashok 
I didn't get, the text is 
> remove the Install entry from being displayed at the live cd desktop.

While we boot the ISO the options appear are:
![mean](https://user-images.githubusercontent.com/15213246/29571935-4d0cedfc-8778-11e7-8329-4e464d270f8d.png)

Now tell me what to remove.

**Comment by abishekvashok** [comment]
@meets2tarun see the word `desktop`; There was a install icon on the desktop as of my knowledge.

Note: There was one before GSOC

**Comment by meets2tarun** [comment]
ok, I got it.
There is no install icon the desktop right now in the meilix LXQt desktop.

**Comment by tabesin** [comment]
Feedback of Mario: please enable install option for live CD.

**Comment by abishekvashok** [comment]
Duplicate of #185

**Comment by abishekvashok** [comment]
Fixed in #221

**Comment by tabesin** [comment]
Is the issue fixed?

**Comment by meets2tarun** [comment]
yes, @tabesin this is fixed.
Thanks to @abishekvashok
