### ISSUE TITLE
Include Documentation for editing meilix-default-settings metapackage

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#147]
- Issue type: Feature request 

### Short description

This issue needs to get solved by improving the documentation by including a section for the new-beginners to let them know the way to edit the OS by editing the meilix-default-settings metapackage.

**Comment by tabesin** [comment]
your upcoming blog post should be sufficient for now

**Comment by tabesin** [comment]
https://docs.google.com/document/d/1oalHUIblSoO-e2VCtBT929JfriWQDdI8q2GfgDXtXxI/edit?ts=599acc70# 
seems ok, I will close this for now, you are free to expand documentation at any time.
