### ISSUE TITLE
Travis deployment fail sometime due to TimeOut Error

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#151]
- Issue type: Bug report 

### Short description

Travis deployment fails sometime due to timeout error and it get solved by restarting the build.
![screenshot from 2017-08-09 10-09-04](https://user-images.githubusercontent.com/15213246/29154313-1956233c-7db1-11e7-87e2-cb6a2e255c01.png)

**Comment by tabesin** [comment]
Apparently it helps to wait the night.

**Comment by abishekvashok** [comment]
You need the reduce the time which it takes to run. Maybe, if you cant do that, we could move of Travis to a new CI.

**Comment by meets2tarun** [comment]
#172 solved this.
