### ISSUE TITLE
Meilix says it is Ubuntu

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#152]
uname -a
> Linux hotelos 4.10.0-30-generic #34-Ubuntu SMP Mon Jul 31 19:37:30 UTC 2017 i686 i686 i686 GNU/Linux

lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 17.04
> Release:        17.04
> Codename:       zesty

**Comment by xeon-zolt** [comment]
let me try the hack to modify it

**Comment by abishekvashok** [comment]
@xeon-zolt `/etc/distrib-release` and `/etc/lsb-release` contains those info.

**Comment by meets2tarun** [comment]
> uname -a

This need still to be solved.

**Comment by meets2tarun** [comment]
The
> uname -a

can't be changed because Meilix is although using Ubuntu Linux Kernel.
