### ISSUE TITLE
ISO naming

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#155]
When you look at:

> deploy:
>   - provider: releases
>     skip_cleanup: true
>     api_key:
>       secure: ...
>     file_glob: true # http://stackoverflow.com/a/28579635/1320237
>     file: "/home/travis/${image_name}"
>     on:
> all_branches: true

you realize that the name of an image is always the same per day. That is no issue with one build per day but may be an issue with deployment. So please verify.

**Comment by niccokunzmann** [comment]
We can also use `$TRAVIS_BUILD_NUMBER` to distinct files from the same day.
