### ISSUE TITLE
plymouth theming

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#158]
plymouth-theme-ubuntu-text
plymouth-theme-ubuntu-logo

are the two theming packages in zesty. I suggest to download the source packages, hack them and generate a custom plymouth-theme-meilix-text and a plymouth-theme-meilix-logo deb package replacing the current artwork package.

**Comment by tabesin** [comment]
The reason behind is that we currently make our hacks on a 3 years old base and don't really have the full picture. Btw. there are other plymouth-theme-*-logo packages for xubuntu, kubuntu and so forth, but it should be easy anyway to see what needs to get changed.

**Comment by tabesin** [comment]
See also:
http://rajeshksv.blogspot.de/2017/02/customize-ubuntu-linux-plymouth-splash.html
https://askubuntu.com/questions/773723/using-update-alternatives-to-change-plymouth-theme-only-affects-shutdown-animati

**Comment by tabesin** [comment]
![bildschirmfoto vom 2017-08-22 16-26-44](https://user-images.githubusercontent.com/10114907/29570431-bc4a3c3c-8756-11e7-8b18-f2fa987ccca8.png)

Displayed for system shutdown but not at boot time for the image regeneration reasons you mentioned.

**Comment by xeon-zolt** [comment]
more strange it should be either at both boot and shutdown or not

**Comment by tabesin** [comment]
The result is exactly what I found online, you have to regenerate the init system for it to take effect during boot time.

**Comment by tabesin** [comment]
http://forum.linuxvillage.org/index.php?topic=158.0

**Comment by tabesin** [comment]
https://ubuntuforums.org/showthread.php?t=2322684
