### ISSUE TITLE
We don't have a license yet!

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/meilix#16]
We don't have a license yet for the meilix project so shall we go for one, if yes let us all express our views here in this issue.

**Comment by Abhi2424shek** [comment]
I personally go for GNU GPL v3

**Comment by yukiisbored** [comment]
@Abhi2424shek We aren't creating our own programs, currently the packages are redistribution of existing projects. So, basically we can't have a license because we don't have a "product"

**Comment by Abhi2424shek** [comment]
When we redistribute we should have a license @yukiisbored and some software require we redistribute it in their own license, hence it was to monetize such problems I created the issue!

**Comment by yukiisbored** [comment]
no, you shouldn't have a license when you redistribute, you give the same license from the original project.

**Comment by yukiisbored** [comment]
Especially with GPL

**Comment by mariobehling** [comment]
@Abhi2424shek @yukiisbored We can use a license. LGPL would be good as it is less restrictive. Please add LGPL.

But also: As a matter of fact the license of this project is not super relevant as all applications used in the distro already have their own license. So the license is mainly relevant for the scripts, which is not such a big thing. 

Hence, let's proceed with the actual code and let's not spend too much time on this hopefully. Thank you.

**Comment by Abhi2424shek** [comment]
@mariobehling sure!
