### ISSUE TITLE
Break out system

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#173]
- Issue type: Bug report 

### Short description

The system seems to breaks out after merging of commits and the desktop seems as:
![ned](https://user-images.githubusercontent.com/15213246/29492152-08056232-8590-11e7-87a1-2bcf441b1a08.png)

**Comment by xeon-zolt** [comment]
did this happen after merging of theme or any other commit?

**Comment by meets2tarun** [comment]
That I don't know exactly.

**Comment by xeon-zolt** [comment]
testing if it is due to theme

**Comment by meets2tarun** [comment]
It is good if it is due to theme because then we can customize the theme quite easily.
![wallpaper](https://user-images.githubusercontent.com/15213246/29493622-a39ab108-85b7-11e7-8752-d4ae1ffd56cb.png)
The black screen is basically a wallpaper and since it doesn't get any wallpaper as mentioned in the location, therefore, the system set a black screen as a wallpaper.
This might help us in setting the wallpaper.
@xeon-zolt

**Comment by tabesin** [comment]
It's all fine. That shows that the wallpaper configuration works.

**Comment by tabesin** [comment]
Please retest https://github.com/fossasia/meilix/blob/master/meilix-default-settings/etc/skel/.config/pcmanfm-qt/lxqt/settings.conf
