### ISSUE TITLE
Depth greater 6

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#183]
I recall that in the build environemtn only supports a 6 level directory structure, however there are deeper setting in the meilix settings package, where substructures of /etc/skel are copied over. How do we increase that 6 value so that elements get included?

**Comment by tabesin** [comment]
E.g. 
https://github.com/fossasia/meilix/blob/master/meilix-default-settings/etc/skel/.local/usr/share/applications/lxqt-about.desktop
is not included in the live system because of the threshold.

**Comment by abishekvashok** [comment]
Is it because of git? >> I don't think so
Or, of Travis?

**Comment by abishekvashok** [comment]
I see here that https://docs.travis-ci.com/user/reference/overview/, Travis uses ext4 filesystem which has a depth of 64000.

**Comment by abishekvashok** [comment]
@tabesin any updates on this?

**Comment by tabesin** [comment]
The unsolved question is why it occurs.

**Comment by tabesin** [comment]
I added a higher git level to travis.yml. Hope this helps

**Comment by abishekvashok** [comment]
Let's see the build.

**Comment by tabesin** [comment]
the problem is that right now we have a black screen issue. Probably grub configuration

**Comment by tabesin** [comment]
I solved that by adding the attribute to the travis file.
