### ISSUE TITLE
Bad Credentials in releases_maintainers.sh

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#184]
- Issue type: Bug report 

### Short description
There is an issue with the token credentials in the releases_maintainer.sh file. 
https://travis-ci.org/fossasia/meilix/builds/268426537#L8798

This means that the file is in the code base but not executed. If the script is executed it is said to remove all earlier releases, so enabling the token is equivalent to deleting previous releases.

**Comment by abishekvashok** [comment]
A PPA with complete repo permissions would be needed.

**Comment by abishekvashok** [comment]
It would be better for the fossasia credentials are used, can you supply them @maruobehling
