### ISSUE TITLE
Enable hard disc install of Meilix

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#185]
- Issue type: Feature request 

### Short description
We require one `Install the OS` option during the first screen of the ISO boot (that was removed and the ubiquity-enabled option to actually install the OS on a hard drive)

**Comment by tabesin** [comment]
when Ubiquity is in place you are free to revert https://github.com/fossasia/meilix/pull/177

**Comment by isht3** [comment]
Hi, how do I start solving this issue as a part of Codeheat? :smile:

**Comment by tabesin** [comment]
It involves installing ubiquity. First you should get familiar with the build process of Meilix and tinker around. Harsh (zeon-zolt) and Tarun could explain you how to make it happen.

**Comment by tabesin** [comment]
As a side note it also involves undoing https://github.com/fossasia/meilix/pull/177 but only when the functionality is actually there.

**Comment by abishekvashok** [comment]
@tabesin I guess we just need to include Ubiquity to be installed along with languagechooser/language-name, countrychooser/shortlist, localechooser/supported-locales during the build and placing preseed.cfg on the CD-ROM and specify its location using the file= boot parameter and fixing the boot menu. Am I right?

**Comment by xeon-zolt** [comment]
@abishekvashok if you adding ubiquity then modify the slides too

**Comment by abishekvashok** [comment]
Which sides @xeon-zolt

**Comment by abishekvashok** [comment]
Oh, got it.
