### ISSUE TITLE
Adding Project mew to Meilix

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#186]
we can add this to the Meilix as it would be a great enhancement for the OS

Project Mew : http://github.com/fossasia/mew
blog on project mew : http://blog.fossasia.org/package-manager-translation-for-meilix/

**Comment by tabesin** [comment]
Why don't you deb package mew before you apply it?

**Comment by xeon-zolt** [comment]
I have added it to meilix default settings but ok let me create a separate deb

**Comment by tabesin** [comment]
Settings is settings, and putting stuff into bin is a different horse and may create debian package management hell.

**Comment by abishekvashok** [comment]
btwo we have apt @xeon-zolt is `mew` really required?

**Comment by abishekvashok** [comment]
@xeon-zolt haven't you solved this?

**Comment by xeon-zolt** [comment]
@abishekvashok can you tell me how to deploy package to apt for https://github.com/fossasia/mew/pull/13

**Comment by meets2tarun** [comment]
What else needs to be done here?

**Comment by tabesin** [comment]
I guess I could close this item now.
