### ISSUE TITLE
Review README.md

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#196]
- Issue type:Feature request 

### Short description
Skim through and update the README.md
Review its contents and make it more helpful and uptodate for onboarding of developers.
As there are right now developers seeking to contribute it provides a good use case to get the README in a shape that is actually helpful and does not include outdated content.

https://github.com/fossasia/meilix/blob/master/README.md

**Comment by meets2tarun** [comment]
I'll improve the readme.

**Comment by tabesin** [comment]
Also mind the remarks of Karl Fogel in http://svnbook.red-bean.com/en/1.7/svn-book.html Foreword

**Comment by meets2tarun** [comment]
Sure @tabesin
