### ISSUE TITLE
For 32bit Architecture install latest working Skype 32Bit package (4.3)

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#199]
The repository has 
https://github.com/fossasia/meilix/blob/master/skype-ubuntu_4.1.0.20-1_i386.deb
but this is not the last 32Bit release.

(there is no current 32 Bit release)

Add the last working Skype package to the repository.

If Meilix build is 64Bit install the latest version of Skype, otherwise the last working 32bit release of Skype.

**Comment by meets2tarun** [comment]
#37

**Comment by 0x48piraj** [comment]
@meets2tarun @tabesin Can I add a script to install 64 bit and 32 bit skype, like we did in `adding-susi.sh` ?

**Comment by meets2tarun** [comment]
@0x48piraj Piyush, I think go ahead with 64 bit.
