### ISSUE TITLE
64Bit apps support with conditionals

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#201]
- Issue type: Feature request 

### Short description

Currently Meilix is 32 Bit for historical reasons. This puts on us several limitations such as unavailability of Chrome and current Skype which do not support 32 Bit architecture anymore. Thev limitation to 32 Bit does not make much sense anymore. Adding 64 Bit support needs to be done in a sensitive way that does not break any custom hacks for 32 Bit.

- [ ]  switch between 32 and 64 bit builds
- [ ] chrome support for 64 Bit
- [ ] skype support for 64 bit
- [x] Init Kernel related issue
- [ ] add items

### First steps

Identify all issues that need to be addressed.

**Comment by tabesin** [comment]
The build script includes an architecture variable.

**Comment by meets2tarun** [comment]
yes @tabesin 
how can we get this file  `image-amd64.tar.lzma`

**Comment by tabesin** [comment]
We have to generate the kernel as we must the i686 kernel.

**Comment by meets2tarun** [comment]
#24

**Comment by tabesin** [comment]
see build.sh
# Script parameters: arch mirror gnomelanguage release
# Arch to build ISO for, i386 or amd64
arch=${1:-i386}

**Comment by tabesin** [comment]
For image-i386.tar.lzma we need a 64 Bit alternative.

**Comment by meets2tarun** [comment]
Are making changes in that file to get the 64 bit version?

**Comment by tabesin** [comment]
For research: LZMA is an archive. Download a 64bit and a 32bit lzma image from Lubuntu, open it and compare. 

Look in the code how we create the i386 lzma image.

**Comment by tabesin** [comment]
one item solved
