### ISSUE TITLE
Deleting of the old build releases

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#204]
We need to delete the old build releases which can be done from https://github.com/fossasia/meilix/blob/master/scripts/releases_maintainer.sh but this is not working due to credentials issue.

**Comment by abishekvashok** [comment]
@meets2tarun can you provide a valid credential pls? or any one on @fossasia/linux-devops-admin

**Comment by meets2tarun** [comment]
I have generated a token with scope as repo but still its not working!

**Comment by abishekvashok** [comment]
@meets2tarun can you commit that, let's see what the log says.

**Comment by abishekvashok** [comment]
>Users with push access to the repository can delete a release.

**Comment by meets2tarun** [comment]
Till now I was using the environment variable, but now lets try directly committing the token.

**Comment by tabesin** [comment]
Just try to execute the script with the access token from your local machine. Don't commit the access token.

**Comment by tabesin** [comment]
Any Progress?

**Comment by abishekvashok** [comment]
I am trying to give it a try

**Comment by abishekvashok** [comment]
@meets2tarun @tabesin I modified the script a bit, now it is giving in good logs,
I can't release releases on my fork as the api returns that there are no releases in my fork,
so, on running on my repo with release id that of fosssia/meilix repository, it shows no content, meaning it is working.

![screenshot from 2017-12-11 20-40-11](https://user-images.githubusercontent.com/8947010/33839497-67c9ba8e-deb8-11e7-8fb2-2f2f78d86295.png)
![screenshot from 2017-12-11 21-10-25](https://user-images.githubusercontent.com/8947010/33839501-68967600-deb8-11e7-84cc-6aa436ea04b8.png)

I have made a PR referencing this issue. To make this script functional we will need a Personal access token for which @fossasia/linux-devops-admin you give me write access to this repository or add your username to travis-ci.org dashboard for fossasia/meilix under the name `UNAME` and put a Personal Access token under the name `KEY`.

**Comment by abishekvashok** [comment]
Please review @fossasia/linux-devops-admin #219

**Comment by meets2tarun** [comment]
@abishekvashok All changes made 
Lets see 
https://travis-ci.org/fossasia/meilix/requests?requestId=96123346

**Comment by abishekvashok** [comment]
@meets2tarun, why isn't curl giving the response, can you dm me with a photo of the Travis ci dashboard pls.

**Comment by abishekvashok** [comment]
@meets2tarun did you try the fix I suggested?

**Comment by meets2tarun** [comment]
@abishekvashok I'm trying it locally first.
