### ISSUE TITLE
Automatic Deployment documentation in readme

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/meilix#207]
- Issue type: Feature request 

### Short description
Right now there is no description for automatic development configuration.

**Yes, I would like work on this issue**

**Comment by tabesin** [comment]
What the state of this issue?

**Comment by meets2tarun** [comment]
@vaibhavsingh97 Are you working on this issue?

**Comment by marvin08** [comment]
@meets2tarun Can I take this up?

**Comment by vaibhavsingh97** [comment]
@meets2tarun I need temp admin access to heroku deployment so that I can configure automatic deployment

**Comment by xeon-zolt** [comment]
**Question** Why do you need admin access for documenting?

- Heroku is not used by Meilix it uses Travis CI for creating ISO and creating release [here ](https://github.com/fossasia/meilix/releases)
- Heroku is used by Meilix Generator for deployment of the webapp 
- check https://github.com/fossasia/meilix-generator/issues/88 for automatic deployment of Heroku issue with Meilix Generator

**Comment by 0x48piraj** [comment]
@xeon-zolt As [fossasia/meilix-generator#88](https://github.com/fossasia/meilix-generator/issues/88) is well discussed, we should close this issue :smile:

**Comment by abishekvashok** [comment]
@0x48piraj they both are different.

**Comment by 0x48piraj** [comment]
> Heroku is not used by Meilix it uses Travis CI for creating ISO and creating release

@abishekvashok ?

**Comment by abishekvashok** [comment]
@0x48piraj yes you are right. Heroku is not used here in this project, the meilix-generator uses it. This issue still exists as we arent deploying doc to gh-pages I guess.

**Comment by abishekvashok** [comment]
@vaibhavsingh97 updates pls

**Comment by vaibhavsingh97** [comment]
@abishekvashok You can work on this issue

**Comment by abishekvashok** [comment]
No, i am not stating to do that bcz i can't really understand what you are saying 😅

**Comment by meets2tarun** [comment]
@vaibhavsingh97 
Please illustrate that on which platform you want the automatic deployment?

**Comment by xeon-zolt** [comment]
lets create a docker file instead

**Comment by tabesin** [comment]
Feel free to beef up the documentation as you like but this issue should be closed and is not about discussing auto-deployment howto.
