### ISSUE TITLE
Make an automatic update for systemlock

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/meilix#21]
The system lock is developed on another repo it would be nice if we could do an auto update from it to here. @mariobehling your views on this pls.

**Comment by Abhi2424shek** [comment]
Any views from anyone would be appreciated.

**Comment by Abhi2424shek** [comment]
@mariobehling should we do this?

**Comment by mariobehling** [comment]
As the development of the system lock has been little recently, I think we need to focus on getting the development up and running before proceeding to more integrations. Therefore I am closing it for now. As we get up to more speed in development, let's get back to this. Thank you.
