### ISSUE TITLE
Custom Ubuntu based on Meilix, little help needed

### ISSUE THREAD

**Issue by fcore117** [fossasia/meilix#213]
I know this is little off topic but i used Meilix script for building cleaner Ubuntu 17.10 that is suitable to me but i stumbled on issues i cannot resolve. I do not know where to turn for help about that and i thought that here i could find someone with heavy debootstrap and Ubuntu core knowledge.

Current problem is that i cannot find what causes that error(error1.png)

You can find extra info inside a (old.txt)

[UbuntuCX_17.10_x64.zip](https://github.com/fossasia/meilix/files/1454523/UbuntuCX_17.10_x64.zip)

**Comment by meets2tarun** [comment]
Sure, thanks for turning yourself here for help, we will try our best.

Would you please tell your approach towards `"Meilix script for building cleaner Ubuntu 17.10"`

**Comment by fcore117** [comment]
meets2tarun: As you see from packages i try to create quite plain desktop with one media player and with one browser, official Ubuntu is too much full of bloat and i found that debootstrab is best way to create barebone Gnome Shell Ubuntu desktop instead of removing stuff.

Like i wrote my old.txt that .iso was success but with some faults. Now i moved my old manual commands to Meilix script but i cannot figure why that error appears. I do not want to customize wallpapers or logos or anything but just make installable less bloated Ubuntu.

**Comment by tabesin** [comment]
First Meilix is currently still 32Bit only.

**Comment by fcore117** [comment]
As i understand that package names should not matter and only thing that enforces 32 bit or 64bit is arch flag. I do not plan to ever use ancient 32 bit anymore in my laptop or desktop, even basic hi resolution graphics rendering will crash with 32bit. 

Currently i cannot find cause what is causing that error on terminal after all packages are installed.

**Comment by tabesin** [comment]
First work on the issue concerning porting Meilix to 64Bit architecture optionally.

**Comment by tabesin** [comment]
Shouldn't you make
    !!!***custom isolinux.cfg and other needed files to image/isolinux/***!!!
a proper comment?

**Comment by fcore117** [comment]
tabesin: this is old and no care needed so proper comment are least use there.

Looks like my modded short script wont reach nowhere and cannot bypass error messages. Closing this and trying to find solutions elsewhere.
