### ISSUE TITLE
Move adding-Susi.sh to script folder

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#215]
This script should be in the script folder, but still be functional, so mere moving the file is probably not enough.

**Comment by xeon-zolt** [comment]
should we add this to GCI ?

**Comment by tabesin** [comment]
why not

**Comment by abishekvashok** [comment]
@tabesin can I work on it as part of GCI?

**Comment by meets2tarun** [comment]
@abishekvashok I say yes, but moreover I think you are capable of solving relatively higher issues.

**Comment by abishekvashok** [comment]
@meets2tarun I would do this, I can't find more GCI tags here.
