### ISSUE TITLE
Update the packages in the repository

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#218]
Many meta packages are auto-generated while there are also the old deb packages in the repo which are being overwritten. It would make sense to update them by committing them to the Fossasia github repo.

**Comment by Shivamgera** [comment]
@tabesin I would like to work on this issue, can you please guide?

**Comment by meets2tarun** [comment]
@Shivamgera Sure, go ahead
There are ways mention for generating metapackages in the readme which where generated before to get the desire package into the OS. Now build.sh contains some packages which override the older one. 
Further @tabesin will illustrate

**Comment by ankurg22** [comment]
@tabesin @meets2tarun I want to work on this issue. Could you elaborate more how to do it? I'm new to open source.

**Comment by tabesin** [comment]
During build time deb packages are generated (debuild) on the build server. They should be added to the repository and the existing packages that are overwritten during buildtime being updated.

**Comment by tabesin** [comment]
The other advantage would be that as long as no changes to these aspects are made one could skip the deb debuild during build time and spped up building, one could test the debs independently on a system etc.
