### ISSUE TITLE
Enhance the meilix logo

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#223]
- Issue type: Feature request 

### Description

The current meilix logo can be seen in the meilix-artwork folder. It contains a not too good logo. We can go for a much better logo. Designs and logos are welcome :)

Note: This doesn't depend only on developing logo and replacing it in meilix-artwork but this also requires replacing it in other portions like the grub boot menu.

**Comment by abishekvashok** [comment]
Quote @marioobheling, 
> please use this: http://patorjk.com/software/taag/#p=display&f=Flower%20Power&t=meilix

**Comment by 0x48piraj** [comment]
We need to make a **ASCII** version of logo ?
It will be difficult to keep both **ASCII** and **standard logo**, the same.

**Comment by xeon-zolt** [comment]
the current logo is not visible many times what can we do with that ?

**Comment by tabesin** [comment]
The non-asciii logo needs enhancements. The other one could be ignored for this ticket.

**Comment by abishekvashok** [comment]
@tabesin i guess Mario wants to have the ASCII version. We could convert it into png and apply it throughout meilix. What do you say?

**Comment by tabesin** [comment]
No he does not.

**Comment by abishekvashok** [comment]
Then we could for some geeky stuff

**Comment by meets2tarun** [comment]
> Geeky stuff

such as:
@abishekvashok

**Comment by abishekvashok** [comment]
?

**Comment by xeon-zolt** [comment]
lets add this ASCII logo to lxterminal by etiting bashrc 
`if [ -f /usr/bin/figlet ]; then figlet -f caligraphy meilix ; fi`

**Comment by tabesin** [comment]
![bildschirmfoto vom 2018-01-03 21-22-14](https://user-images.githubusercontent.com/10114907/34538396-8c1118da-f0cc-11e7-9481-cd7027b8f08a.png)

**Comment by tabesin** [comment]
![bildschirmfoto vom 2018-01-03 23-59-22](https://user-images.githubusercontent.com/10114907/34543629-26be6bac-f0e2-11e7-802a-3ed37ff77523.png)
![bildschirmfoto vom 2018-01-03 23-57-01](https://user-images.githubusercontent.com/10114907/34543630-2c608e6e-f0e2-11e7-8937-066fc81e06f6.png)

**Comment by ParthS007** [comment]
![meilix1](https://user-images.githubusercontent.com/24358501/34558113-c1e3dfe2-f162-11e7-9cfe-28ad9b2cb9d6.png)

**Comment by ParthS007** [comment]
@meets2tarun @xeon-zolt @tabesin  @abishekvashok  Your views. Thanks

**Comment by tabesin** [comment]
Looks excellent!! Is there a way to take a dark orange or another colour than black? (the reason and context is that the logo ideally will also be the start button for a light and a dark theme in Meilix. Black on dark theme does not look very good and black on light theme provides too drastic contrast)

**Comment by ParthS007** [comment]
ok @tabesin  I will do the changes.

**Comment by meets2tarun** [comment]
Great Job @ParthS007

**Comment by 0x48piraj** [comment]
I too can contribute some mockups. Should I @meets2tarun @xeon-zolt @abishekvashok ?

**Comment by abishekvashok** [comment]
Everyone is free to do so.

Your design looks awesome @ParthS007

**Comment by ParthS007** [comment]
![meilix2](https://user-images.githubusercontent.com/24358501/34565873-83d64724-f182-11e7-91ac-771f28a8ca5a.png)
![meilix3](https://user-images.githubusercontent.com/24358501/34565877-8562559c-f182-11e7-9f17-3ebffff74f48.png)
![meilix4](https://user-images.githubusercontent.com/24358501/34565952-c1fe7f80-f182-11e7-9e02-f17f396c3b74.png)

**Comment by 0x48piraj** [comment]
## My Mockups : 

![image](https://user-images.githubusercontent.com/5800726/34565988-df57affc-f182-11e7-9c15-191ccf042be7.png)

![image](https://user-images.githubusercontent.com/5800726/34566001-f159b8c6-f182-11e7-9f9a-460e032d8afa.png)

![image](https://user-images.githubusercontent.com/5800726/34566020-0986f01c-f183-11e7-8a40-9f022e079084.png)

Ping @ParthS007 @hpdang @mariobehling @abishekvashok @xeon-zolt @tabesin

**Comment by xeon-zolt** [comment]
@0x48piraj your mockup theme will look awesome on installer slides

**Comment by 0x48piraj** [comment]
Thanks @xeon-zolt

**Comment by abishekvashok** [comment]
All the logos seems to be nice, we can wait for some more if we want and pick from these

**Comment by vaibhavsingh97** [comment]
My Designs 😅 
![1](https://user-images.githubusercontent.com/8705386/34612206-ba14bdee-f24e-11e7-997c-ad85e437c151.png)
![2](https://user-images.githubusercontent.com/8705386/34612208-ba6c127e-f24e-11e7-8e13-1d53e434d1d0.png)
![3](https://user-images.githubusercontent.com/8705386/34612210-baafd644-f24e-11e7-9cfd-5c3a59f10e95.png)
![4](https://user-images.githubusercontent.com/8705386/34612211-baf2e010-f24e-11e7-8e96-0616025c2405.png)
![5](https://user-images.githubusercontent.com/8705386/34612212-bbbd60f6-f24e-11e7-9b4a-80528b6cb73b.png)
![6](https://user-images.githubusercontent.com/8705386/34612213-bc03ecb0-f24e-11e7-9fa8-1664fefceed1.png)
![7](https://user-images.githubusercontent.com/8705386/34612214-bc9ee972-f24e-11e7-9cc1-e9501e36075a.png)
![8](https://user-images.githubusercontent.com/8705386/34612215-bce1ef24-f24e-11e7-8a1a-4572a7347809.png)
![9](https://user-images.githubusercontent.com/8705386/34612216-bd25acdc-f24e-11e7-93c8-e286d32abbfc.png)
![10](https://user-images.githubusercontent.com/8705386/34612217-bd71d3aa-f24e-11e7-8268-f407bf937388.png)

**Comment by 0x48piraj** [comment]
I loved the jarvis styled one :sweat_smile:

**Comment by xeon-zolt** [comment]
if we can have some kind of voting for these designs

**Comment by tabesin** [comment]
@vaibhavsingh97 I like the crown style "M", I combined that in a (immature) mockup with the great one of ParthS007
![meimockup](https://user-images.githubusercontent.com/10114907/34638398-c5ceba28-f2ca-11e7-9631-2c026de7b405.png)

**Comment by vaibhavsingh97** [comment]
@tabesin I have all the templates
![5](https://user-images.githubusercontent.com/8705386/34638469-fd748170-f2f1-11e7-934b-eef2c677b032.png)

**Comment by abishekvashok** [comment]
@vaibhavsingh97 the pink one looks superb

**Comment by 0x48piraj** [comment]
So many designers here :sparkles: 

Superb mockups :100:

**Comment by tabesin** [comment]
So let's implement.

**Comment by vaibhavsingh97** [comment]
@tabesin Why you closed  the issue?

**Comment by 0x48piraj** [comment]
@xeon-zolt 
I can create a application for voting!
Should I ?

**Comment by tabesin** [comment]
Sounds great!

**Comment by 0x48piraj** [comment]
I'm on it! :100: 
I'll deliver a fully functional website in a week.
Sounds good ?

**Comment by tabesin** [comment]
Please also provide svg files

**Comment by vaibhavsingh97** [comment]
@tabesin Only PNG/PDF can be produced. I made these designs from Canva

**Comment by vaibhavsingh97** [comment]
@tabesin Which logo you need in SVG?

**Comment by hellozee** [comment]
![logo](https://user-images.githubusercontent.com/12135951/39918316-b2bc3c24-552d-11e8-89d9-047348465d23.png)

Here is my shot at fully converting the above logo to vector 
[logo.zip](https://github.com/fossasia/meilix/files/1994785/logo.zip)
