### ISSUE TITLE
Enhance readme with screenshots

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#224]
- Issue type: Feature request 

### Short description
Let's have some nice screenshots of meilix, add them to the readme.md file so that it will be a pleasing look for on lookers.

**Comment by duttaditya18** [comment]
Working on it!

**Comment by xeon-zolt** [comment]
what about GIFs showing small features of the OS ?

**Comment by duttaditya18** [comment]
@xeon-zolt Nice idea!

**Comment by tabesin** [comment]
just do it but no need to keep this ticket open for months
