### ISSUE TITLE
Release maintainer script does not delete tags

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#230]
- Issue type: Bug report

### Short description
The release maintainer script currently does a good job by deleting old releases but does not delete tags, should we delete them?

**Comment by xeon-zolt** [comment]
Yup cause they will increase with number of usages of meilix generator

**Comment by abishekvashok** [comment]
Finding if the github api supports it

**Comment by meets2tarun** [comment]
I can even see older release. They aren't deleted yet.

**Comment by abishekvashok** [comment]
Intresting

**Comment by abishekvashok** [comment]
@meets2tarun any references

**Comment by tabesin** [comment]
As far as I can see the release_manager script was never successfully run on the main repository... (I deleted quite a few legacy builds manually)

**Comment by abishekvashok** [comment]
@tabesin the log highlights that it can find only two releases which are not longer than 10 days old. So it did'nt delete them on the last build.

**Comment by pranav1698** [comment]
@tabesin @abishekvashok the releases maintainer script does not delete the releases as well because it is getting this error `expr: non-integer argument
`
