### ISSUE TITLE
Error when trying to build Meilix using build.sh

### ISSUE THREAD

**Issue by alekcacko** [fossasia/meilix#233]
- Issue type: Bug report 

### Short description

I am trying to build Meilix using build.sh but I get error.

[This](https://pastebin.com/xM4KPMUp) is the output when running build.sh.

### Environment

 - Operating system: Ubuntu 17.10
 - Software version: 
 - Software source: Github Repository

### Steps to reproduce

1. Clone the repository
`git clone https://github.com/fossasia/meilix.git`
2. Make build.sh executable
`chmod +x build.sh`
3. Start  build.sh
`./build.sh`

### Expected behaviour
I expect to have built ISO.

### Actual behaviour
The error described in Short description

**Comment by xeon-zolt** [comment]
@alekcacko thanks for the update it's due to changes in mew repo let me fix it by removing mew for while

**Comment by tabesin** [comment]
Please comment out the lines, do not delete them.
