### ISSUE TITLE
Zesty releases are not found

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#235]
- Issue type: Bug report

### Short description

when checking travis logs of pull #234 
the error is 
> Failed getting release file http://archive.ubuntu.com/ubuntu/dists/zesty/Release

### Environment
Travis CI 
### Steps to reproduce
try using build script from pull #234 

Zesty release is not found in http://archive.ubuntu.com/ubuntu/dists/

### solution 
switch to a different build

**Comment by tabesin** [comment]
Zesty is EOL support for Jan  2018.

Maybe just this package source. 

Could you change your pending PR in the way that you keep the Zesty to Xenial migration just focussed on this ticket and split from the other aspects?

**Comment by xeon-zolt** [comment]
creating 2 different pulls for both

**Comment by tabesin** [comment]
It seems Canonical actually removed Zesty from its servers.

**Comment by meets2tarun** [comment]
Should we go for latest build release now?
