### ISSUE TITLE
Refactoring filesystem manifest

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#237]
Please check if this could be simplified and for what reasons we have this cp chain here:

> sudo chroot chroot dpkg-query -W --showformat='${Package} ${Version}\n' >/tmp/manifest.$$
> sudo cp -v /tmp/manifest.$$ image/casper/filesystem.manifest
> sudo cp -v image/casper/filesystem.manifest image/casper/filesystem.manifest-desktop
> rm /tmp/manifest.$$

**Comment by vaibhavsingh97** [comment]
@tabesin Yes, I can reduce the number of commands

```bash
sudo chroot dpkg-query -W --showformat='${Package} ${Version}\n' > casper/filesystem.manifest
sudo cp -v casper/filesystem.manifest casper/filesystem.manifest-desktop
```

**Comment by xeon-zolt** [comment]
@vaibhavsingh97 go ahead

**Comment by tabesin** [comment]
Seems like we have to reopen it or revert the changes.

**Comment by pranav1698** [comment]
I would like to work on this issue
