### ISSUE TITLE
Create amd64 build

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix#24]
As far as I can see, creating a meilix amd64 requires the following:

- [ ] add the file `image-amd64.tar.lzma`
- [ ] do not install i368 packages
- [ ] add amd64 variants of the i368 packages

```
meilix$ ./build.sh amd64
./build.sh: ERROR: data file /home/coderdojo/meilix/image-amd64.tar.lzma not found
```

Questions:

- [x] Is it possible to use the same image files for amd64 as for i368? Answer: Yes, it is. But EFI boot does not work.
- [x] Could we just copy the files for the amd64 image from the Ubuntu amd64 iso? No: Does not work.

**Comment by niccokunzmann** [comment]
I was able to build the amd64 version by removing the deb packages and using the same image-i368.tar.lzma.

**Comment by niccokunzmann** [comment]
I am currently working on the [amd64 branch](https://github.com/CodersOS/meilix/tree/amd64) - there is a release.

**Comment by niccokunzmann** [comment]
Current state: EFI does not work with the image files from i368.
Next step: copy from other ubuntu.

**Comment by niccokunzmann** [comment]
Copying from ubuntu mate did not work. A `vmlinuz.efi` is required.
32bit boots with efi, 64bit does not.

**Comment by Abhi2424shek** [comment]
Want some help?

**Comment by niccokunzmann** [comment]
Sure!

**Comment by niccokunzmann** [comment]
@Abhi2424shek You are invited: 
https://github.com/CodersOS/meilix/invitations

**Comment by niccokunzmann** [comment]
I am looking forward to have just one Linux with a customized filesystem.squashfs. I have been trying this for two weeks and now I am really frustrated. Maybe you have some new methods and ideas on how to go about this.

**Comment by Abhi2424shek** [comment]
Should we use UEFI? @niccokunzmann (GRUB)

**Comment by niccokunzmann** [comment]
Please try if it seems like an option.

**Comment by Abhi2424shek** [comment]
It's convention is to use the bootloader to call the kernel file, grub would do the needy, but we would need to chroot somewhere and Ubuntu and most other distributions offer a live cd to do so.

**Comment by Abhi2424shek** [comment]
@niccokunzmann some updates?

**Comment by niccokunzmann** [comment]
No.

**Comment by meets2tarun** [comment]
Does the work still going on?

**Comment by Abhi2424shek** [comment]
Yep, I was experimenting yesterday, I think @niccokunzmann is also working a bit.

**Comment by niccokunzmann** [comment]
I am not working on it.

**Comment by meets2tarun** [comment]
@niccokunzmann I saw commits in your forked repo of meilix. Make a pr.

**Comment by niccokunzmann** [comment]
You can use them, it is GPL.
1. Add a my repos as a remote
2. pull from that branch

**Comment by meets2tarun** [comment]
Don't you make a pr of your work till yet ?

**Comment by niccokunzmann** [comment]
I think, I could not get it to run. So, I abandoned the work.

**Comment by meets2tarun** [comment]
@niccokunzmann  please make a pull request of your work till yet, then we will see that how we can improve it.

**Comment by abishekvashok** [comment]
@meets2tarun any updates on this one?

**Comment by meets2tarun** [comment]
@abishekvashok No updates.
And it's going to take time and I don't know how to implement that.

**Comment by abishekvashok** [comment]
aren't we using i368 as well as 64 bit packages?

**Comment by meets2tarun** [comment]
Could you please mention those packages?

**Comment by meets2tarun** [comment]
Could you please mention those packages?

**Comment by tabesin** [comment]
Related https://github.com/fossasia/meilix/issues/117
Chrome does not install as i386

**Comment by tabesin** [comment]
In build.sh:

> 
> # Script parameters: arch mirror gnomelanguage release
> # Arch to build ISO for, i386 or amd64
> arch=${1:-i386}

**Comment by abishekvashok** [comment]
@tabesin but I tried to run the script with those parameters but that's not working.

**Comment by tabesin** [comment]
Of course not, so what is needed is:
1. add a 64Bit Kernel
2. Make an conditional everywhere we have 32 Bit packages right now. If 32 bit do x if 64 bit do y. 

y is usually less complicated.

**Comment by xeon-zolt** [comment]
Adding kernel alone does not solve the problem

**Comment by xeon-zolt** [comment]
i am working on it by recreating everything from scratch again

**Comment by tabesin** [comment]
Tarun you could already work on the "2) add the conditionals" issues if you want. It is also a good and simple task for a SoC student.

**Comment by meets2tarun** [comment]
@tabesin Yes, I'll work for the conditions and then just integrate it with the rest but how would we able to get `image-amd64.tar.lzma` ?

**Comment by xeon-zolt** [comment]
@abishekvashok copying do not works , if you can please try fixing error in https://github.com/xeon-zolt/meilix/tree/newstart as i am not getting free time to debug it

**Comment by niccokunzmann** [comment]
Here we have collected a list of ways how to NOT provide 64 bit support:
Please add your ideas here:
https://docs.google.com/document/d/188_yWUeRguFkKuoVQgNwBGKllsK6n-V1t5XR7tzSEWI/edit

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/commit/9c3e88f1878155c3a825f84858c190c05839a212#diff-0b83f9dedf40d7356e5ca147a077acb4R16
