### ISSUE TITLE
Add-on Susi not found

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#240]
- Issue type: Bug report 

### Short description

Add-on Susi has been installed into the Firefox browser by @xeon-zolt through a script but it is not found inside the extension of Firefox in meilix.

**Comment by tabesin** [comment]
Please add details, which script, where.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/blob/master/scripts/adding-susi.sh

**Comment by tabesin** [comment]
okay https://github.com/fossasia/meilix/blob/master/scripts/adding-susi.sh
What do the logs say?
Is the double 
cd ..
line correct? Does this script get executed at all?

**Comment by tabesin** [comment]
root@travis-job-27f1f698-11ad-4fee-a95d-be63b58c8566:/# # Installing SUSI Deskto 
p package
root@travis-job-27f1f698-11ad-4fee-a95d-be63b58c8566:/# dpkg -i SUSI-desktop.deb 
[Aroot@travis-job-27f1f698-11ad-4fee-a95d-be63b58c8566:/# dpkg -i SUSI-desktop.de[Kb
dpkg: error processing archive SUSI-desktop.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 SUSI-desktop.deb

**Comment by xeon-zolt** [comment]
SUSI desktop deb is different and firefox extension is different
