### ISSUE TITLE
Multiple window managers present and no default one in skel

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#242]
- Issue type: Bug report
### Short description

multiple window mangers are present and I personally dont feel very good about it ( WHY ? )
we should use only one window manger as default if any window manger installed during addition of packages which should not be the case we should also have a default window manger config inside skel
### Steps to reproduce

1. Boot in live moe
### Expected behaviour

should show the DE LXQT without asking for any configuration
### Actual behaviour

 asks for required configuration

![screenshot from 2018-03-11 22-54-57](https://user-images.githubusercontent.com/4529442/37256446-d35491de-2580-11e8-9ce0-a36abe647bf4.png)

**Comment by tabesin** [comment]
Default should be openbox. 

Why does KWIN get installed? Is that a dependency of the LXQt packages?

**Comment by xeon-zolt** [comment]
we should add quick fix by adding Openbox as default in skel and keep the branch open to find out which package causes that

**Comment by niccokunzmann** [comment]
#281 removes kwin
