### ISSUE TITLE
Metapackages needs to be rebuild for zesty update.

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#25]
We are at zesty with trusty metapackages which are broken for the update by PR #41 which updated the base to zesty, we need to update the metapackages to move forward.

**Comment by Abhi2424shek** [comment]
@maeiobehling it would be awesome if you could give some info about he contributors of the metapackages, some of them doesnot have the changes file.

**Comment by Abhi2424shek** [comment]
Contacting @vanhonit

**Comment by vanhonit** [comment]
@Abhi2424shek How can i help you?

**Comment by Abhi2424shek** [comment]
@vanhonit OS has been updated to Yakkety but the metapackages have not been done so. I could update some of them which have .changes file but I can't help for those without them, can you help by updating them?

**Comment by vanhonit** [comment]
Let me try. I am not sure because I did it 3 years ago.

**Comment by Abhi2424shek** [comment]
Sure @vanhonit :)

**Comment by Abhi2424shek** [comment]
It now needs to be rebuild for zesty as of the latest PR and issue #41.

**Comment by meets2tarun** [comment]
@abishekvashok I need your help that how to rebuild the meta packages for the changes that we made?

**Comment by abishekvashok** [comment]
We need a .changes file to update them. It's the same tool that is used to update as is used to build them

**Comment by meets2tarun** [comment]
.change file contain checksums , how can one alter that?
Would you please illustrate the way to update and build? Any link will be greatly helpful.

**Comment by abishekvashok** [comment]
This should come handy: https://blends.debian.org/blends/apb.html

> .change file contain checksums , how can one alter that?

They are gpg keys and are autogenerated.

**Comment by meets2tarun** [comment]
> This should come handy: https://blends.debian.org/blends/apb.html

Thanks but it doesn't contain anything such as rebuilding of the metapackages.
P.S. I went through all the related pages of the link.

**Comment by abishekvashok** [comment]
Extracting the metapackage using any tool like the one mentioned in the link or equvis and building it again.
