### ISSUE TITLE
Building fail of Travis [ReadTimeOut Error]

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#254]
Travis is failing build due to Readtimeout Error.

This may be due to the large log.

Idea: Decrease the tree command so as to complete the log between 10k lines.

**Comment by xeon-zolt** [comment]
this is not the reason of failure it is the reason you are not able to see the reason of failure (Hint check how we saved all logs of build command to a text file and mailed it do if Travis stops showing logs after 10k lines the logs will be saved in a file and mailed)

**Comment by meets2tarun** [comment]
ok, we mailed the log.txt using Travis API to the user.

So what would be reason of ReadTimeout Error?
I though the idea by the `terms` used in the error "ReadTimeout".

**Comment by tabesin** [comment]
Right. I suggest to pack the log file first.

**Comment by meets2tarun** [comment]
After disabling the tree it is still coming timeout error https://travis-ci.org/fossasia/meilix/builds/380840502#L9457
commit: https://github.com/fossasia/meilix/commit/fd320dfa642557ca5ede91da8b15cb86a7d3db8d

**Comment by meets2tarun** [comment]
https://blog.fossasia.org/updating-of-linux-standard-base-lsb-and-shorten-of-log-of-meilix-build/
