### ISSUE TITLE
Cleaning of the Meilix repo

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#262]
Today Meilix repo include lots of files (deb files, packages, metapackages) which can also be included through script and this make the repo more crumble and dirty.

So it needs to be cleaned and well maintained.

This is an epic and several difference PRs may be needed to get it sorted.

**Comment by tabesin** [comment]
Could this go https://github.com/fossasia/meilix/tree/master/dists/trusty ?

**Comment by tabesin** [comment]
I think the whole image folder could be deleted given the line in build.sh that deletes it. But please check locally first.

**Comment by tabesin** [comment]
What was the result?

**Comment by meets2tarun** [comment]
Yes, I tried locally as well as on Travis.
I gave error without the image folder.
https://github.com/meets2tarun/meilix/commits/clean
