### ISSUE TITLE
Meilix ISO boot into black screen

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#270]
I tested the latest build of meilix and found that meilix boot into a black screen and where there nothing is visible.

**Comment by meets2tarun** [comment]
I drafted the release and when I checked the ISO, I found that ISO on Mar 18 is working and beyond that none of the ISO is working (all lead to a blank screen).

<img width="1163" alt="screen shot 2018-06-01 at 10 55 45" src="https://user-images.githubusercontent.com/15213246/40822561-6856123c-658a-11e8-9e5c-e60366922885.png">

Then I searched for the commit for the date 18 Mar which doesn't seem to break the ISO and neither of the any commits made on 3 April.

<img width="1165" alt="screen shot 2018-06-01 at 10 58 33" src="https://user-images.githubusercontent.com/15213246/40822680-eb82dbc2-658a-11e8-8555-f07095102eb9.png">

**Comment by meets2tarun** [comment]
<img width="618" alt="screen shot 2018-06-02 at 16 45 41" src="https://user-images.githubusercontent.com/15213246/40873897-1ed6cbfe-6686-11e8-81d0-2f0630212802.png">


I'm getting this error while booting now

@xeon-zolt @niccokunzmann @tabesin

**Comment by xeon-zolt** [comment]
ramdisk is missing

**Comment by meets2tarun** [comment]
Now all the ISO are facing the same issue:
https://github.com/fossasia/meilix/issues/270#issuecomment-394080123

I tried on different virtual machines, still the same.

**Comment by meets2tarun** [comment]
I tried these ISOs

https://github.com/fossasia/meilix/releases/tag/untagged-582f0863209939748aab
https://github.com/fossasia/meilix/releases/tag/untagged-bd1005bc8c0941c5aa1f

**Comment by meets2tarun** [comment]
I even tried the drafted ISO released by commits:
https://github.com/fossasia/meilix/commit/cbe27e491c57633da2abeda456d718faff6bcbdd

**Comment by meets2tarun** [comment]
I made different branches where I revert the commits and releases ISO then test it
https://github.com/meets2tarun/meilix

**Comment by meets2tarun** [comment]
 ~/repos/meilix   master  git log --format="oneline" | grep -oe '^\S*' | sed 's/^/- /'
- 1d1e75d398e74c9ecd0f7358832639b77e014d78
-
- 12089627181c7613c6883423a75862b27408ed7a
-
- 5663c2438cde5e9ba8609264513f915bdf1d8cbb
-
- 94db27c887ac90601f37a6f04241f45b209bb8a2
-
- 6d1a80f43a28938ce1274745735982a45f874aa4
-
- f428fdc43075b300d84144ebf95327ce6c4b2dbe
-
- 5d1122ada9f91face6f9b66a1c99902b02c1f051
-
- ed821e9c668961d7c0da1dbf99757cf24a804fb2
-
- 2960c28c10d1b62fbecc8e498cb5ac9abaa502a6
-
- 1afecab4fdac46a3ff479fb017294488d52bfee7
-
- 64ff851d53f95c0cc3c82d573650e96f30865ab9
-
- 156cb53f621467aa8b3752866898e2d5a94a61da
-
- fd320dfa642557ca5ede91da8b15cb86a7d3db8d
-
- f1dbfa5da4e5e7974547bd58685ba2e326ac26ad
-
- 6e2ba36a61f544ccbf781b2edd89dc4a2a6dac95
-
- 89b2861878a5f0b16821a52ee959a83d1c31f3b4
-
- e230eb02e0ea5aa8deba696b19cce5266a43a322
-
- 9af5326b8704a20a871189e41748650a8169ac4a
-
- 0f88ff92fe4088543695986828122e8c975a4b8c
-
- a27d1c666532e970f333a97f7f90c096b1c46d1f
-
- 2ecdd3d661c49dd4ec1fdb48359ffcc9bd65ff44
-
- b6f74978ae0c2a54d50034b7ecaaea12eb41a887
-
- 1e925ac9d60279e2611618871089c478f444d691
-
- ffd7fe655ca5450a719f1dab7bdf7e1e503e8dd7
-
- ba2a50ae289cdf3cdf81e85e96d45add1e8ed277
-
- 3cc11f9cc50e7687da520a083997fa3dc5fbe24c
-
- 0eb7866c560e8592a67e0fc0e370fc8d3f6bc13b
-
- 682dd83d619d745a441c0e5a10aceff7f0b6f3d2
-
- 49476161d9b7dc2280d7bc0b6a431c0c1044ee31
-
- ef0930013741081680ded70439c3340c25ed9b87
-
- e9272f24103bc063595b07146c1702865c182206
-
- 9b8af058b8a88f8e0d992e71a0b5137a59d70e7c
-
- a18150ba7425221925caea0c7af0b62637856ca6
-
- f9de7669003f32c3736a6be8948a4e1879a8df17
-
- fb57a4d58c734c168731da1f4da6d5bd3c6606d4
-
- afea109cff07af77bcea19bf5d5a878921d6bbf0
-
- cbe27e491c57633da2abeda456d718faff6bcbdd
-
- 6f287eadadb8df65fb07d6ec2a8ef979a1a423ef
-
- 353a4b50c2db9fe3b881ebe78f6228153e04f6b1
-
- f9b76fbd5b9074c579e6501f7614a74bc831192b
-
- b732384c48ed05d7671802b1eac25b32914532c1
-
- 826d2e9cae2423d560f74c8ca00f38e7ce8aba34
-
- dd17d09adade4488a8b66c8cedbbfa81a5b74b35
-
- 1b73ec05806835bd206b600abf72a894f0379f4e
-
- ea5a6c04b1a78160c5eeffb8c1fd11ce41e4c225
-
- fcb34cc8a9bdf5475f89fcfc51793fca420a41c4
-
- dcb04c60b88dafc3d596fda421eccc2a0e83e612
-
- 3ac461bd188b25e3a9e201d236ac1312f03717b4
-
- a56017a21b5eeb5c75ac8c61ffe1197c636102c3
-
- fe811e13948b35c9413ab815e0dd231e64f8416c
-
- 747a469ac80ab61e272d8622e650e151d3f3e3ed
-
- 415743dfa69c77c2fc1803bda8e7a5d3bcc84778
-
- 698c996e38249661b07e5281fa272541e451aa5c
-
- fee2252882e9f3c4a34a0940d263ae7886fe9a96
-
- 5d830852376c2a816d34d0e6a91440ee24a75a6e
-
- da2224291950e6b2c9732c6a5d96ad1a0263d526
-
- 4da796a8e71c4e6e2c95c0ca0b7687514b2f120a
-
- 06e3c55fe80fcdb07adf156c55024125caa82407
-
- 03696ecbede7d1fe5798d9c89bd1ae948b487ed2
-
- aab9845f65ebde2d1f3346ba2905c1c2455e6fef
-
- 22b68a35e9e4460ebc6f4f820665af177fd70b19
-
- 1401c696dece152fd1de07cb4ba4635e1fe9c62f
-
- 02d96b1e9dcf4093ebf58c1d6a0fa75b32e988de
-
- e8fd796a0b3ad3f65a725fc7e31863d28f1d7359
-
- 74583d8fdf86543be06e7ff465ed4966d710194b
-
- afc5cd8276f5a47a4a446e171beb4a38eb989416
-
- 44d27cd988d43a807731c1d9ca82cf04594a95f2
-
- 718374b4a52c16c6117d10bc73323b37da210872
-
- 736b381e652d3debe5b1bbf466bc3a599067e464
-
- df2ad3bc72816bfa4600e432d6ba1334f13488d9
-
- 6746d106b4f56aaa4fc65aeb4d0d89bd44cce3c2
-
- 1ba480054cb144d15f03eaacd4d526eaf48a112f
-
- 137964f1d7e62d843d951c849b7a83a070e9e5a5
-
- 64958031b5b6f6be0f99ada5d396ed0ccf71ce73
-
- 2028ef9ee5ddca2d6404d971a61b2a9ef44b69a4
-
- c11a85b9cacdfae38c7a30874fb7528239c3430c
-
- 3e8d82b28d200de0e7379982feb76fd7ccc97070
-
- b83624d06bac3f71a84ed6a923d5a0b09c3a733f
-
- ab804a3b52fcf5119405b8adb46290b71235276f
-
- cf90e0e5e05c5632644ce3c3c29abda9eab6741b
-
- 9e27d5abf98858f5d512d919f6008c98a19cb061
-
- e9b2573d4a9476fc66259ef0c5f356976ed80c94
-
- ca0567e50258a6ff1b2799d7f4e93ba67c9d6461
-
- 24630fe368bcc3986c2ab72d66413f86944ff796
-
- 09aa1550f41eca7415242ded06b4bae005c28f79
-
- a484e42ea7c2242148641bedc918cd3aa87a1bb1
-
- 83a08bf809c826ac6cfa365e01f4140c6976623b
-
- 321dfaa7921327d4816d33eeeb5f1e4390db9a02
-
- 77d4f75b78fd5fc00da6069a59aee088ca801208
-
- e2af6aaa018b965dd7b4c19c1acaa69d56660ad5
-
- d80eae80eae45cda158945cf1d049cee6250f1bf
-
- 7ea8fdf99343e3a4139378daa0f60586448765e4
-
- 386a5f35f4751546f316592695887b651bead1bd
-
- 673f61b432d78fde4185b4e31f9868f00c8de36d
-
- 5250b7e9faad370cced5afb0d782b8292a5080bd
-
- b38bc65812caa4e8681aac6f87bf3ff64af6ecd0
-
- 6bd646a835136d5a6b5d40026de18a8058b60120
-
- 5bde1d354af42fb608302957161a70f34fa37f2d
-
- 56e7c3de3878720fbb576a25ce9cb5c2dd5095a4
-
- 188a1df9b67ff76c4781680dd45496e6f2199d42
-
- 64b8f237c5014d8d7f126fa8ad2284fe20bad248
-
- c990a2500f3bc4cee883691a693d258d29266c52
-
- 7e74d5684ba73343e90526fabdc01f9c5c460751
-
- b12078c63a21a4e3b220eff582209c7c39a4f5f1
-
- e5b1a3f23cd2c3f648bae58d18c7bceb373e4416
-
- d80c150d0a588f3fa62dcb7349285a67cd63fe0e
-
- 52abefa6796fd00066951d8f26066f6443d89377
-
- 588f69ee95b4eb62ef6be36dc638fb19b6928e6e
-
- 38abc727960afffbc2983530133077739caa268a
-
- ba0c0a9338c956651ca3852ccf50f987cb0f37ae
-
- f4137a4ff293e86e2d96751141e5b5d6424a4600
-
- e27b5099038e165354436b520e0da1d965c0bc58
-
- 7cdf93ac396435462b5be7bbf1ced80f21597bcc
-
- 671a71b373912112270fa76c9610fc4aded7675e
-
- 4e0d3ca2b9f7bbaafd71d0c46d848a65b39edc88
-
- 37734c63a37df5f94da2e5ff03cdae4fa25393d4
-
- 9b5095945e9820f0d7817e9b80be0bb8157d95d1
-
- dd753445c73e5f9f85fdec66abe2e64120570192
-
- 16d86123e3909e7daabe37e406b0690da4b74e29
-
- 5ad2065c8b0c22fd2ed0ec595ff9187463532fcc
-
- 0130856926323533aad8124c3522e46d954e750a
-
- 023cf69cb124ca259849c19eb21247a46ee42ef5
-
- 396e81ec4d4113acd7e89910566c472af4735330
-
- 49a7870717d1dcbfeb6ef7099332a4eb7fa58b37
-
- aedef9e85b5fdee19797056eacc7eaa2f91eefe9
-
- 025f9e6a6d0769c891745c4ba5ebf593b9cc7c1a
-
- d62c4d934c55bb9a11c3b4120fedd085f0dad5a8
-
- b07bd0fc84b66cb596e54d389998b588ad03d6e9
-
- 9fcd78284305a21861833e152855427292281edb
-
- aa7d0b3980b2e9f2876abd7d717f8e1f133ae47f
-
- dca6e3b373ca68ccb57082e506bfb16bab0ff0f4
-
- bbedb9ac843c874d28519ea29ea91e30e8b5ab86
-
- 72a9195a7abe2443c8d9a8ce7fce1e6ed4794925
-
- f720f988622119551a807ccd6d1faef12c66f4c9
-
- 45e87db545e5cdf0c11298dbde302d408811050b
-
- dcfb0b4d5c1e8e62e6ccbbc0f46ab66da33cb737
-
- c10fc98979e8e26251f58a8207c3146d3df3e600
-
- fafb82463ed0ca49d9d4b8de7bd8df0bace64845
-
- d21fc5a983aaa3a927bb3597ca4394e5380169a5
-
- 6acd431cd6b4491be980a47915d2e727c1f3b352
-
- cf43dc6757716ceed0457ec88c00882795015f54
-
- 9fab31b1f53d560a1e39c40880431d78d3aa9c2b
-
- 98b656493047088ed825633ab0b0a618061021d2
-
- 642792f60b273292e17a0b16dcc3fab514840b5f
-
- 1bdf8de732a575c200e3a9e6b2ecb93c758e64da
-
- 9f94b21abf643707879d61003bf66c49bf78c844
-
- d3833bc0b7d9fa55ef26067961bb35ec436d90df
-
- cf732ba12aa8ca56c29b9cc5a05b518da371b9d6
-
- 692ed5fdf75dd100d055add2d3211e4c9d01e5c6
-
- d5dba2046a3c7ae1cff1bbeed9e118873ccff2dd
-
- 6453c2fc20ba1564aacdbf4ec271fc89406c8967
-
- 6be837eae312e24a61f8a421cf70dc61657fbf4a
-
- 35c7c3dd5a799212c4ee13bbfbd94a628d7c327b
-
- 531c77d2a4c8795168a77494f7cc9fac42e77692
-
- 2ecc2c8f9b06306b7ba7d8a07ced7b080e3fba7e
-
- 33203fddac725e12179b16d5ffabb83d9abc7a29
-
- d30cc8aeb1023230c84a32dc5772c71ec2bf4d01
-
- 2f4fa5cd159314d4556354efd30312a61afcb6af
-
- 7eb67ee402aa82f9f6b9a41fef5168c15004cc28
-
- ff69642a2fc5a231fbb80d97361e2618f0c128f0
-
- 7638bd0b8cc5d3a8a2decc59c942e7b00a7b4143
-
- d587fda5fc65af22eb72b52668df06d6ec58df19
-
- a74b8fba00ae68d40713e79e0e954187bc533670
-
- b5d0e803c89a7249602722a6c8994f284ed0b460
-
- 9a4f4f792d88744414fb914e0b3433d09baecd9c
-
- c978a9b79678e3fc0d916012c6e649a1e6d11a38
-
- 4052e3637a9f41e56e728be18b41a8a2c29d5b95
-
- 582e1f1cb07f4c79f2d65cba22502e811d49b427
-
- 694a4e821dfbbdefdfe892ea2a0bca4a850f84ae
-
- e0b46dccf59cdc4d4afbf0b05c1231da2bb6a13e
-
- e0a7619a6e908695755006e929115c345b3da974
-
- 1861464cb8adc7e0780a8a789bd9e9f830a5b740
-
- 4f6c60932e9ad2eb7b6c44460f10166c922cdc3e
-
- ba51412b35c2f54f2a3fc21629e865377a415cff
-
- 0aff67ad4b6a2ec19c180c02b460ce0c250cc8f7
-
- beaada7471ecf1e5e57c5f9cdf763ad59e73b5cb
-
- 8501cdb2bcfc1cae6862641d07ae9bf79971c96a
-
- fc25b35b0ae19de04c175e6a1a3ff217919815ef
-
- 13ed06c1875283939e7ee12fbd16c55ab36e50bc
-
- 9c2b8f0d1959a39e30187f404f9fceeb7836623e
-
- dd117d3a0f193a13a2f7d707f473c26ef38d1263
-
- 4251963ae85c09ae5da9f7203e9b840c01aeaebb
-
- 60afd43d66e772f0b37f44f272a6fa9d352dc91e
-
- f1eaa3908c127f4aa211361d6debab1047744449
-
- 4507f3ec249d6497f1a88ae40ef6a35872a475c9
-
- 9ff5c7d597861d33b2651f2a002e99efc9394fde
-
- b05b22af5bb3cd00f0618eca90206a4fc3084079
-
- b9153559fe66bf9faba4321f805b6061a9f4a07c
-
- bd1524cc39b97dcaed2b573c9a9db0eb34d68af7
-
- 35af6a033962509f6af05864dbed450c582ed486
-
- b5b71d42db8bd2f8addf3f0f7a35686511a8e44c
-
- f572908fed44fc612dd490e373e8e1c5bc4f09d8
-
- 32c99105d19092021940c3e143936592c8c5aa52
-
- 42903e8ccd41a8c20da05194227171329a91955a
-
- d0fc43f2e6c090d0b16ed988daf4f5f943ac390b
-
- 5b9281fbde840b26aa9d3ba18dd77ed2d2fc5815
-
- 07a88470e78505595c504e89b9fd22f696b1ac71
-
- 25d30bb5204f15f530a557b8a5a9f1f937b76a51
-
- ee6c5ac5d38314a0ab7dfc505b32591b4eea1f47
-
- 04ea507356f28482afa133cd2380fcd9037f1bce
-
- 3ae7bee6064fa112570fc4ccef123feb0b400861
-
- 726ea355358569ab9265b58d8ec75e6bccf9e0b5
-
- 6ae67249fef318b964a28de7181fb50b5cec2376
-
- 2411e627730e9e7e20e229bb9ded4d11c0905e5d
-
- 7c3532cf0baeeffddf84856561e10464dbed2214
-
- 949acb3116069ab639c64aba0891ee7deb1567e1
-
- 30a080856ff3cb53b17c39dc2eb55f95ad09e675
-
- 3cad16d9f64592f84b685873126e1aba59d26798
-
- efba0805eee431d8dcb28d4dc0c07e83e4c227d3
-
- 5d4908b0bb4a0ff777aaffb5940ea7f68417b139
-
- 9673d55d93080d6a5716fc67366a170619422e7f
-
- c70881959e00333af821b0038500e877c2e6cc06
-
- 465168494994c2346f7087eb20ce06999b9471b7
-
- 0df9ff4b1fa6f8b3b6725ce55be990c1a1652e7d
-
- e92e77746820ddcd1b51153df05c38333bbccfa4
-
- c71302e768e136e19a85eb36e87b23d72e338b9b
-
- dc8da4a5e90d039e6d434c8f9bdbe865d09be460
-
- d20adaae9b208705afa628d3901a8735ea35dd2f
-
- b9f7b834b90930ee3fa46cd2d1d0d4e9e9df3dd0
-
- f9ff42564fe6cb5f7f8b11abe1c33afe1470287d
-
- 7ddff0349169e3868d8510993618306c8c0f7796
-
- b9713ecbf30d99cb1f4ba07190e333291e8bdc88
-
- 2a5b1d4b942eb8320aac6c673305c8af3ab2a83d
-
- 0db50f4a073da2ba6674465c01bfa7c46ec0005d
-
- cc20564a8a065012a78cd4d88da8e5979edf1130
-
- d31fce8fb11d25567b354684a8707d24bbbffb59
-
- f1756ab90a355d03be283fd56219962883fb3f05
-
- 640f7440098be879ef29dc5d767b755582110b06
-
- 7975552ac1a2bd87bf4008e5f760f5c6aabb275d
-
- c24694c6ab79eaa5aebba9679a1cd6fc13219827
-
- ff7126a0444967be84245bb18fe9bbefd06cd3d8
-
- 082c5b00672db5342aa07e25e6750ecb9f395f5f
-
- 8c21f1f779275932157d1fd9b6f306e29679ba1f
-
- f9beb81d2bf883340173bdb077f2457ef3a635e2
-
- ed13c30384ad47c3f4927cb4d3ddc0e3128ed82d
-
- af05364cca2b2ba402545ef45ef907377c00f3cd
-
- 4d1f3fc626bc00250ab90e29a2587a3a7189481b
-
- 7cbcb5cde3f92d02bc2d9df613530552d3415af2
-
- 153997386c1ffb178b83da3dccb5cd07f8e87b25
-
- 0860541154a241fe4aa0ebd8aafec9da4446ff3c
-
- 2224f2dec9c7681c40d1156286452564a4560ee8
-
- 4ab97cdb74b9b6bc43b3e7bc0823d69cc712a828
-
- 36736cee2d755ff91cdfd644aed0dcd35ee0e89c
-
- 0d3a8e0143fae5a06507d6be77d2eed87d8116a9
-
- 31b1eddd649484146d35d07e6f4aff88dd3bec59
-
- 53965ac9ff00cc26e647da5896bfe32657acdfea
-
- ad8790af2afeda403e12a40793d343669e28f7e6
-
- 4dc729cbedd703e319422a02bf6a24edfb9d4e34
-
- 37e7d51830e7650cc0c07b338fc22cb0e5112151
-
- 0b09e5e4c836c8249259792e1e0c86a5ca6ee77a
-
- c75f8345a74d836770e5d9e56959446911768d30
-
- 8cbae6cbe8d4f8f85176700b39bb488886018f03
-
- 035f12650a0984f17007182e60262954c9dd9a77
-
- a82ac2bda859a68868523a9bfbf02ad346678471
-
- 683317cf05bd54f00e86f61b5c11ae5daa80f59e
-
- 5876e252d7ca2ab7729565d6f8d30c6ac9527bf1
-
- 1708276cd18d373e5b875dd49b503bdf2139bf1d
-
- 93a5ccf487d12df4eaf3ba09c29977c11e147805
-
- 8f1c01dddba7dabc85a22af4f10db8a919f2a06b
-
- a94fb25cb481196cb5ad81682b0ae8aa4753210d
-
- 7d89e21636419fdb84423e8f25e48f7331daaf1d
-
- c316da0d78de2cf9b7be981ded6e58222530e73b
-
- a49ce2b0b043d321ba3b6071b3cb2dcbbde4e11c
-
- d7cbc26327423783e4e79c19bf3ba4c74f9d0e3b
-
- 290e65a24980d670a02b57545f2a6f8b0bd992a5
-
- e032867be31a83f036862fe651e1ab76253db25e
-
- d01469b29e68e9a56e4ebe31e01b5d0cd6e7c480
-
- e776328d9aaf2ec9c98ce64d5239e34154b57b76
-
- ea61ad922ed3834a1b6c0ca7f69b88713cbe86a7
-
- 1d4804979b6100ca27212e0b33638ef4d912d7d0
-
- 3338b23dd7e050e5131ed8f3971905b0da6887a7
-
- 597ace13beae14db90871074ec4c2148d263872c
-
- 4f74c183dcf2fb1491edcbb16658e82037ac9bae
-
- 3487889ca81be29c1e4fb74d2aac9de503da492d
-
- 023a8035467bbc658fd61f3c6daf6f090d65b651
-
- 98d50b9bd60ee788ccc0148239d687f91d85dd4b
-
- 7b664915b728e49c90c74ba0fd2e55c327e7a8d7
-
- 01cfc36d4040ee089cc1b5805a2430ac3018212b
-
- 7474b95726ff7fc175caece4107d793559a46d43
-
- f74b00d5745907eca83ad3ba1edc8a25240b5cb2
-
- 6319eeaa6b7e6b8371a3508f1903b9b8e214f3d0
-
- 1b03a679c75bd6eb5b4c975a743c7300894ed094
-
- 8f39306c1d694fe89cd5ecf8045c08a470b11745
-
- a73cbf754cb1124a77baac15b4833deb00c9f286
-
- 38e722a3faca2f811621bc6c3273eda39a919367
-
- 1975ce4ac2d2b985b03150863d7e4b0834455f28
-
- 35b9c28273174e8af92b744dda720c0497374dae
-
- 7d2f63ebda4aefeb9bbd46fe894d7293cc3d45b8
-
- 49d12e6a093e51e987e1e6e91b54e1952294b687
-
- 7d401d2cccc4092f017cede7628c87b7e3f4b14a
-
- 1c3d5d8de06cdc43dff9bd5c31001a3cb00105fc
-
- 2c7689580dcf810c90dfeb838badd8bcb9eedb45
-
- 84c765c8769190d493561aff8e499eecd8aec503
-
- 744b92083c8f0a770d1367b517e0ae37d4270cbe
-
- 46d7441c88f7f64b735f41ab97ecd8fb7b7c1cd9
-
- 3be7bad4528a40625fea75cceb742eaa4948105e
-
- ad91f1d5a3726ebfe6e82ed049669a3380ee0712
-
- 69e901d7a76afa678068cfae96684c80ea11135d
-
- 7d6e9a9e3f0340be21f7041a5b6338ebe2bc0f16
-
- 7f774f1a6860a97611ebd07f05b452cd3f542d2c
-
- c7e1d89cf86eaf52e9a454c180e03cddbf3c199a
-
- f21482f77cfe65031acecf463b3c7468fa164b55
-
- 667750c6d878a3c257050138f4977f298eb32840
-
- ca43e0b4356b15fe8944b4aa248c7f12c11faf5c
-
- 1d36e87b0ee8f52994a9a43a1e95b045fcbb7ab5
-
- d10a29a8ee8a636bdc84e92098e97b06214c6ba9
-
- 51d5c6fca66a5d58368906753d7e37f881cd2461
-
- 2f854f24fb9cdeed1412f1e1d6e98a13cd1a242a
-
- c825a716f0c09409eccf258f6cee0ec611d3057f
-
- b6545e54c46a151dc14c63dd22c6de59777dc0cf
-
- 321f881221cae7076893d373e9911ff3b8ea3fab
-
- 1fa04b2cb783392f78181c479a9351d3abb5d26e
-
- ffa6996fcd302a4c822dff68bd026505f58581d4
-
- 59c0557d94ef68a24aeb4ae6a81bad221cbd8b4d
-
- f18adb74997363e74eaedeed6f718bb23a3ed1ed
-
- 81a6ec5d12026f9ebfdf8618abfeff2e0a8cf1e3
-
- 66c2cc0e5df3b41311361840e87a7e6e83976bcb
-
- 55e3ff8d19f420e77d3f48264aba60df88bc4971
-
- b0b5816447d3054666c1f0cb5f98c0523a544e8d
-
- fdfb8d49e8eab64c86a12e6de11fc386c24b3305
-
- 1ec93380a289a58dc0c29330042517e7a0c4179c
-
- b5d8d35858a4647c1541ebd4f653b39219b0507c
-
- 84c1640728bb615f003af89ee750e9fedfbe8341
-
- c1435bd59a0d1a8a0b6ca617615f8118d5fe7ae6
-
- 51e755de1a1eac4915048f05c523b7e7cb180874
-
- 94580fd843ab0402c1e2870576e6eca781abd527
-
- ca7431fc975decbe94f51177e759cf6e08ec059f
-
- 12f80d01d84a5f0d9c2f3f59ce5dc40d5403a92e
-
- efae64d5c8331656e8fcd25d72d006f80eb24b40
-
- 2dd012f629bd975c8aaae772c94fd01ccf54a50a
-
- 128219263327cc29dd25e8d9ad64a60bceef3bc6
-
- e7d63bf511d18f78bca8f2e8b3800f91ac026816
-
- 5a25fb54430b9c7b1cce43a952acf6e2a71ca9da
-
- 5d9aa2853c5bf7ae6640b4f38c0b9cdb03685401
-
- 03be574bd08579847253dffdd9700fec66afdaac
-
- fb2de423f4084578719e43d7c9a408828067fa5a
-
- fe3d0ac62eab72e67ae210c09d83b203df69abcf
-
- d410d54efe26b331122d3d9e1bc4ea62b2b2b04d
-
- 288ae994f01d07f42a195b10e5a50bd5240d7b34
-
- 97b864b8d306070d06b58d94b988b30fa8603866
-
- 40aaa14782f9ef975b00bbb9b0fdaaf429cf8d28
-
- bf39fa0e37b9f893251e8aea1b63c216a414d000
-
- f2ef9df5d5761ef9d30c00a3b2fd75db59af3f17
-
- d77e7b1b374f1fdbf56526423149b91e19f482c3
-
- f4490bfca1668b6425a563c39bc5fdc9367828ad
-
- 6b80cb207ef3db5efc8f6d89cbc1ce0123830784
-
- 68ca80ee2a9b2eca1d324d07bd2b1ac627d35565
-
- 14420fc0cb43170ae894c22faa24bd1672180254
-
- 211464f3dc6287094fc8ffc9e5483f6575e67e2c
-
- 0cfd91c6a61c663bdacad0b0f9398ce889c74b6e
-
- ccfee7714c8d9e3cb1121b5def26efc63996c8a4
-
- ed869635f7928ad939b398b19a8c651b28b42249
-
- 6750ca48161144420a405bfad6b1e1303df9d262
-
- 302239040b611a8671bfe1de23cf54145c0ecb5f
-
- 3d580e76e85f6ae2a674beee811d35fd81a8c303
-
- bce9a0ab786f4e620ec758ab4d460b4c093bd179
-
- b9cea0bbe939ee747b0604ca46f77143afabea2b
-
- 8bd78f3acbda71dfbb956fcc780e47a4a725400a
-
- 2d757f04341abf1abcc002b4363563c0910119a7
-
- acd523a52af8e15b716e6484edb2f8cee8a5f1fb
-
- 2701fffb47bcf2caf43cc17724e33aadc2a9f85c
-
- 30d0f0e152c16b5c3386fc3f9bc2481883025cc8
-
- a1efa4c45384498110cda3ce8428ae9c5bc7c428
-
- 0df2b40e720b645784ae48c906407445fcbb0dbc
-
- 67b9719fc61a7c2ed7466cce1a2d9a8d0d192a5d
-
- bf04fd4982f0462459a5c392c16468cbc4426e45
-
- 859d3633acf0691c83395cb780e3f2de073df8f3
-
- 23fda3884d73dc22b73e33d3a6dd3968373df130
-
- f3ec97c7ec4ccef0dcc7a57052881aa4f46833a0
-
- 6f249231b887e9e7d48912fccdf832783f722f0c
-
- 2bf2f0914ac53a5dbf9a1012a8570988a5ccc4b3
-
- 397ee47d5ff65e6eaea77f0b54b07e69b9c3e4b9
-
- 26b39ae6cb860f323f35c73dce55cdfc1b835b83
-
- 8860b25f98eda5772ca68d7309462da8722ce4f2
-
- ccdcef7933991951318025ace46a21059fd34973
-
- 6596ee7e4d08a1dbb4a0752c2e4418e2bf07bea5
-
- 36e955817766250c882a08bb4888683a856af38d
-
- 91c25addeedac6a181f9a030441958199e009ae6
-
- 285a60c103caef4cc0eb10dbdc19f844935d9033
-
- 31633ac4883121dd5e766012042dbda2c92298a6
-
- 11b2bd6b9550837ac15c54b8d4108acacc772722
-
- 81b8640870943ef5c6fc4bec3084f9fcdf4b0618
-
- 25e5f761811690a829c86e99be22e3373da51e91
-
- ec007d21491ccce1a6256de1c74fb179b01a6aee
-
- ec3760c38cec06b68eef4b6c971309e23a02c67c
-
- 0c5f03e162125ee5e3fa8b62d9835619bc40fa14
-
- 38ec965c1627eb85c0889a9e0faa856887cd4112
-
- e715038ceaad5d194d563ea0ad600dcc49d3914b
-
- 13f05e33b371a9e29c1e83cac844a33bde1a6c6d
-
- c8f9c5ace3edfb569ba7ab9e02461f7f16c312bc
-
- 20739a949dd92fa31097b7ba355de2cdf158a5ad
-
- 33ca455f37e5ddecfaba6601a27f3daa53a1a406
-
- 2fdcc766d02c0dab8d7f4ff5e927f2c62541d0a3
-
- 899038b525a145e4481a15a7c788e2ad50e621c2

**Comment by meets2tarun** [comment]
@niccokunzmann 
Please look here https://github.com/fossasia/meilix/issues/270#issuecomment-395822235 , I tested and update the content of the comment

**Comment by meets2tarun** [comment]
Should be shift Meilix back to that working commit or try to find out whats breaking the ISO?

**Comment by meets2tarun** [comment]
If I searched for the error, it doesn't seems to be error from the ISO side.
Even I tried building the ISO locally and test it, it is giving the same result.

**Comment by meets2tarun** [comment]
@abishekvashok Can you look and help us?

**Comment by abishekvashok** [comment]
It looks like it's more than a hardware error than the error on the iso side. Try running it on another computer if you could.

**Comment by meets2tarun** [comment]
Yes, @abishekvashok 
I done that but seems to be the same, sometime blank screen and sometime https://github.com/fossasia/meilix/issues/270#issuecomment-394080123 as a result.

**Comment by meets2tarun** [comment]
I tried different qemu, virtual box, VMware on different machines.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/issues/270#issuecomment-399629896 This happens after this commit https://github.com/meets2tarun/meilix/commit/eb89388e322f83ede36511e00176ce3dd268ae7e

**Comment by niccokunzmann** [comment]
Another Idea:
1. initramfs is a small linux shell. please use ls and cd to find the file containing the file system. in this black shell (initramfs)
2. try to mount the ISO file manually

**Comment by tabesin** [comment]
Local mount:

sudo mount -o loop path/to/your/ISO_FILE.ISO /this/path
sudo umount /this/path

/this/path must exist of course

**Comment by tabesin** [comment]
You could mount the March 18 (good) and the closest April (bad)l ISO image and run a diff between both directories. the result will possibly large, but you can then narrow the differences down. In particular I am interested in everything related to /boot/ and x configuration

**Comment by meets2tarun** [comment]
I updated the build to artful and tested, its the same result again.
https://github.com/fossasia/meilix/compare/master...meets2tarun:zesty?expand=1
https://github.com/meets2tarun/meilix/releases/tag/untagged-0feab5825af660eb3579
<img width="1680" alt="screenshot 2018-07-05 at 10 53 58" src="https://user-images.githubusercontent.com/15213246/42304158-75d9a96e-8042-11e8-9510-34a9c547f435.png">

**Comment by abishekvashok** [comment]
> Another Idea:
initramfs is a small linux shell. please use ls and cd to find the file containing the file system filesystem.squashfs. in this black shell (initramfs)
try to mount the ISO file manually

Try this maybe @meets2tarun

**Comment by meets2tarun** [comment]
This commit https://github.com/fossasia/meilix/commit/dce3b086f3056744db603b788797e2a31bb3e914
gave the following screenshot
<img width="1618" alt="screenshot 2018-07-05 at 22 48 50" src="https://user-images.githubusercontent.com/15213246/42337844-9329d602-80a5-11e8-9f2b-d5a303295d19.png">
