### ISSUE TITLE
Meilix is asking for password

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#286]
Meilix ISO boots into this screen and it asks for password.
<img width="1618" alt="screenshot 2018-07-05 at 22 48 50" src="https://user-images.githubusercontent.com/15213246/42337844-9329d602-80a5-11e8-9f2b-d5a303295d19.png">

**Comment by tabesin** [comment]
Let me check the code.

**Comment by abishekvashok** [comment]
Try "live"

**Comment by abishekvashok** [comment]
Nah, I mentioned to try the password "live"

**Comment by meets2tarun** [comment]
Yes, I tried `live`, it still not working. @abishekvashok

**Comment by tabesin** [comment]
Where did this screen come from?

**Comment by niccokunzmann** [comment]
I have these ideas:

1. Is there a way to choose the root shell as login? This should be possible by passing an additional parameter. This way, you can find out the user name.
2. You can create a user in the chroot and which is saved inside the squashfs. This user should exist. useradd should be the command.

**Comment by tabesin** [comment]
cut -d: -f1 /etc/passwd

**Comment by tabesin** [comment]
See this in the casper script:

# Allow to override USERNAME and HOST based on media information
    # make it skipable by setting FLAVOUR= in casper.conf
    if [ -f /cdrom/.disk/info ] && [ -z "$FLAVOUR" ]; then
        FLAVOUR="$(cut -d' ' -f1 "/cdrom/.disk/info" 2>/dev/null | tr '[A-Z]' '[a-z]')" || FLAVOUR=
        if [ -n "$FLAVOUR" ]; then
            HOST=$FLAVOUR
            USERNAME=$FLAVOUR
            export HOST USERNAME
            sed -i "s,USERNAME=.*,USERNAME=\"$FLAVOUR\",g; s,HOST=.*,HOST=\"$FLAVOUR\",g" /etc/casper.conf
        fi
    fi

**Comment by tabesin** [comment]
resolved.
