### ISSUE TITLE
Need of custom scripts for Meilix to run trigger by webapp

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#289]
### Expected behaviour

We need script for Meilix to execute by triggering the webapp

### Actual behaviour

There are two possible ways to do so:
- [ ] Downloading scripts from Generator webapp (present in script folder) to Meilix repo, and then execute it.
 - One only need to touch only one repository.
- [x] Directly commit scripts in Meilix repo.

**Comment by meets2tarun** [comment]
cc: @tabesin @niccokunzmann @abishekvashok

**Comment by abishekvashok** [comment]
Those scripts can be embedded by modifying the iso at the build trigger time at the web app repo can't we do that and keep this clean?

**Comment by tabesin** [comment]
Have all the scripts in the meilix repo. Like scripts/add_chrome.sh

And just hand over the variables. So -pseudocode ahead - if install_chrome=yes execute add_chrome.sh

You then have to hand over a single file with the variables (I call it a "receipe").
arch= amd64
wallpaper = http://mydownloadlocation/wallpaper3.png
install_chrome = no

etc.

**Comment by pranav1698** [comment]
@tabesin this again can be closed
