### ISSUE TITLE
Need for an working ISO

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#294]
ISOs generated are currently unstable for unknown reasons. Meaning from one release to the other issues emerge or fade away.

**Comment by abishekvashok** [comment]
Instead of this, we should try to curtail and write a way to test things.

**Comment by abishekvashok** [comment]
https://fedoraproject.org/wiki/How_to_test_updates

**Comment by tabesin** [comment]
We have another ticket for this. Let's close this one.

**Comment by r0mflip** [comment]
IDK but we should probably deleted the old tagged versions of Meilix. GitHub hosts us for free but you know...
