### ISSUE TITLE
Create package of mew

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#299]
Build.sh included the line:

> #Adding Mew to the Meilix
> #chmod +x ./scripts/mew.sh
> #./scripts/mew.sh
> #create package of mew and use the package only instead of creating package here

Please build a package of mew in case this should be included again.

**Comment by xeon-zolt** [comment]
@nagpalm7 you can read Debian wiki for how to create a deb package

**Comment by tabesin** [comment]
see debuild.sh in the repository. Also consider build.sh and chroot.sh.

Start with helping the meilix-artwork repository effort to get an idea. Once this is done we have a model for an independent  mew repository packaging effort.

**Comment by meets2tarun** [comment]
you can also have a look here https://github.com/fossasia/mew

**Comment by tabesin** [comment]
So let's close this here.
