### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/meilix#30]
Deployment on master branch is not working. Bad credentials are the cause of the error. Maybe something happened with the API key,
@mariobehling can you check the API key please?
Thank you.

**Comment by niccokunzmann** [comment]
@Abhi2424shek Please provide a source for your claim.

**Comment by niccokunzmann** [comment]
Is it this? https://travis-ci.org/fossasia/meilix#L8814

**Comment by niccokunzmann** [comment]
You updated the access token https://github.com/fossasia/meilix/blame/master/.travis.yml#L21
So something changed.
Without being complete, this could be the reasons:

- Your API key was revoked, check in the api key places
- Your rights in this repository are restricted. Can you still push and create a release?

**Comment by Abhi2424shek** [comment]
Was it my token? I still have access to push and deploy, let me check if it is revoked.
