### ISSUE TITLE
Error in release_mantainer script

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#301]
- Issue type: Bug report 

### Short description
In Travis the line
./scripts/releases_maintainer.sh: line 45: current_day-09: value too great for base (error token is "09")
shows up.

**Comment by abishekvashok** [comment]
Working on it.

**Comment by abishekvashok** [comment]
Upss we need to convert it into integer, i.e, 09 into 9

**Comment by abishekvashok** [comment]
Solution: `Prepend the string "10#" to the front of your variables.`
