### ISSUE TITLE
Plymouth skipped for 64bit

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#302]
- Issue type: Bug report

Travis logs for amd64 show:
W: plymouth module (/usr/lib/x86_64-linux-gnu/plymouth//meilix-text.so) missing, skipping that theme.

**Comment by tabesin** [comment]
Check with other plymouth theme sources, if a symlink is needed or any.

**Comment by abishekvashok** [comment]
https://ubuntuforums.org/showthread.php?t=2322684

**Comment by abishekvashok** [comment]
It's a needed symlink.

**Comment by tabesin** [comment]
https://github.com/fossasia/meilix-artwork/issues/19
