### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by ramantehlan** [fossasia/meilix#305]
- Issue type: Bug report

### Short description
I was trying to build ISO file, but it failed.

### Environment

 - Operating system:  Linux Mint [4.10.0-38-generic #42~16.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux]
 - Software version: Master Branch
 - Software source: [github/ramantehlan/meilix](Https://github.com/ramantehlan/meilix)

### Steps to reproduce

1. Go into the repo.
2. Run build command ./build.sh

### Expected behaviour
Should create a ISO.

### Actual behaviour
```Bash
$ ./build.sh
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
W: http://archive.canonical.com/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: The repository 'https://download.docker.com/linux/debian sylvia Release' does not have a Release file.
E: Failed to fetch https://download.docker.com/linux/debian/dists/sylvia/stable/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:4 and /etc/apt/sources.list.d/docker.list:1
```
### Usecase

Well, just trying to build a ISO file.

**Comment by abishekvashok** [comment]
@ramentehlan make sure you have a proper internet connection.

**Comment by ramantehlan** [comment]
@abishekvashok, I checked my network again, my internet is working quite well. In my humble opinion, I think it's a problem with some configuration, also the (Travis)[(https://travis-ci.org/fossasia/meilix)] build is failing as well.

**Comment by abishekvashok** [comment]
It's about the apt repo mirrors then, I am looking into it.

**Comment by abishekvashok** [comment]
Sure.

**Comment by tabesin** [comment]
a) I upgraded build.sh and apt sources from "xenial" to "bionic" and also added a new lzma image. The build does fail for unknown reasons. Sure, a revert is here super simple.
b) what you have above is another issue related to your local Linux Mint install or docker image, Travis uses Linux Trusty to build. Only few tools have to be installed on the build machine.

**Comment by abishekvashok** [comment]
To get over Travis ci, can we run a docker pipeline in the container running the latest ubuntu? Or should we update existing packages to give backward support.

**Comment by ramantehlan** [comment]
*This is embarrassing* 
I was going through the source code, I realized it run `apt update`, and that is what was causing this issue. Maybe we can have an error catching function in place to do so, I will look into it. 

@abishekvashok, @xeon-zolt This issue can be closed now.
