### ISSUE TITLE
Refactor Plymouth themes

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#306]
Meilix currently has two Plymouth splash screen themes, logo and text. The respective files are found in the artwork folder. The naming meilix-artwork follows the convention by debian and *buntu distributions. At present both debian packages are generated during build time of Meilix and then installed. We want to make this generation (debuild) independent from the meilix build process.
.
We want to do it as follows:
1. Build the theme packages from a Github repository of its own [meilix-artwork](https://github.com/fossasia/meilix-artwork) instead from the Meilix repository
2. Rebase the meilix artwork package by investigating contemporary plymouth artwork packages (e.g. apt source xubuntu-artwork)

First debuild the debian package on your local machine, then make it work on travis and github release (cmp. Meilix repository for a clue). Finally deploy generated debian packages to apt.meilix.org

**Comment by xeon-zolt** [comment]
@tabesin can you create one repo for Plymouth then

**Comment by tabesin** [comment]
https://github.com/fossasia/meilix-artwork
