### ISSUE TITLE
ISO no working

### ISSUE THREAD

**Issue by ramantehlan** [fossasia/meilix#309]
- Issue type: Bug report

### Short description

I was trying to install Meilix in virtual box; using the [untagged-2d4d350683a1b9499066](https://github.com/fossasia/meilix/releases/tag/untagged-2d4d350683a1b9499066) release. It ends up on a blank screen and that's it. 

### Environment

 - Operating system: -
 - Software version: VirtualBox Version 5.2.18 r124319 (Qt5.6.1)
 - Software source:  [untagged-2d4d350683a1b9499066](https://github.com/fossasia/meilix/releases/tag/untagged-2d4d350683a1b9499066)

### Steps to reproduce

1. Create a Virtual machine.
2. Add the [untagged-2d4d350683a1b9499066](https://github.com/fossasia/meilix/releases/tag/untagged-2d4d350683a1b9499066) release.
3. Once you start it, it won't work.

### Expected behaviour
It should get installed.

### Actual behaviour

![peek 2018-09-23 14-37](https://user-images.githubusercontent.com/29037312/45926491-20913700-bf40-11e8-8e4d-95d2df43ff51.gif)

**Comment by tabesin** [comment]
Thanks for your interest.
First on https://github.com/fossasia/meilix/releases search for
"Latest release".

This release should get you at least towards a SDDM login screen.

Please check.

**Comment by ramantehlan** [comment]
The ISO I used is the latest release. I even tried to build it myself, but even that is not working out.

**Comment by Gauravsahadev** [comment]
I am facing the same problem while opening it virtual box.

**Comment by rpotter12** [comment]
I am facing this problem.

**Comment by tabesin** [comment]
build log see https://www.travis-ci.org/fossasia/meilix

**Comment by rpotter12** [comment]
@tabesin I have set already set it to the 64bit but still, it was showing black screen.

**Comment by tabesin** [comment]
build log see https://www.travis-ci.org/fossasia/meilix

**Comment by tabesin** [comment]
Let's assume that the issue is that we mistakenly removed files from the meilix-default-settings folder.

Check if the release from my outdated fork https://github.com/tabesin/meilix is booting into a LXQT desktop.

If it does download the meilix-default-settings folder from my fork and the meilix fork and compare the contents of boths. Maybe you find sth useful.

**Comment by irahulcse** [comment]
@ramantehlan 
There could be some possible reasons like you need to update your fork repo(as some files are changed earlier now) or might be needed you have not updated to the 64 bit version of Virtualbox.
Could you pls tell me your default Operating System.

**Comment by pranav1698** [comment]
@tabesin facing the same issue, 
There is no iso release in your releases section: https://github.com/tabesin/meilix/releases

**Comment by pranav1698** [comment]
I tried running the build.sh filebut even that is not wotking it reaches to a certain file and then stops working

**Comment by meets2tarun** [comment]
@pranav1698, 
I think now it's working, we are able to login to the desktop now.

**Comment by pranav1698** [comment]
Please can you add a gif of the process till we reach the desktop

**Comment by pranav1698** [comment]
I also made it to work to get to the lxqt env from one of the patch:

![meilix 1](https://user-images.githubusercontent.com/34754265/48665428-0f921b80-ead4-11e8-9695-ffd4666dc8c9.gif)
@tabesin @meets2tarun what do you think?

**Comment by tabesin** [comment]
Seems we fixed this. ;)
