### ISSUE TITLE
Change fossasia/meilix project link

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#318]
- Issue type: Feature request 

### Short description

The Github description references meilix.fossasia.org which is an alias for apt.meilix.org. 
I suggest to remove that.

**Comment by tabesin** [comment]
![image](https://user-images.githubusercontent.com/10114907/47296525-c1901200-d612-11e8-9d24-8af4b594b55c.png)

**Comment by abishekvashok** [comment]
Any admin, @mariobehling may be.
