### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#32]
The readme.md of the repository needs improvement.

**Comment by niccokunzmann** [comment]
Can you clarify what needs to be achieved to close this issue?

**Comment by meets2tarun** [comment]
I am trying to build this and it includes most of the steps which are not included in the readme.md .
First of all, the step is to introduce to travis.
Then that generation of token and encryption of it with travis.
Editing of .travis.yaml. 
Or you can help me with much better way.

**Comment by Abhi2424shek** [comment]
To build it, you need to run build.sh and not Travis. @meets2tarun, you have to understand Travis is like a VM, a Continuous Integration(CI), which is used here for Continuous Delivery(CD). The token and other things are out of scope here.

We have an issue #1. Pls follow up there for additional documentation. That's the documentation you need.
