### ISSUE TITLE
Cleanup 3 - Remove dists/trusty

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#324]
Remove the superfluos dists/trusty folder.

**Comment by irahulcse** [comment]
Change the ./build.sh File.
Go and change the line 
1.[ -d dists ] && sudo rm -R dists/trusty
to
[ -d dists ] && sudo rm -R dists
2. Save the file.
3. Go to the Command line and again build the file with the same commands written in the build column of readme.md.

**Comment by tabesin** [comment]
Awaiting the PR ;)

**Comment by pranav1698** [comment]
This is resolved in the current build

**Comment by tabesin** [comment]
no, the folder is still in the repo.

**Comment by tabesin** [comment]
git rm -r directory_name
