### ISSUE TITLE
Resolve the cannot remove confilict of melix-default-settings

### ISSUE THREAD

**Issue by irahulcse** [fossasia/meilix#329]
- Issue type: Bug report during build

### Short description
![image](https://user-images.githubusercontent.com/34218254/47965620-5b25dd80-e06f-11e8-800f-268e1bd96eeb.png)

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: Linux

### Steps to reproduce

1.  Might be we need to work as a sudo(root user) not really sure about it.

### Expected behaviour

Error of  not able to remove the directory during the build of the Melix through travis and command line both.

**Comment by tabesin** [comment]
This shall not be removed.

**Comment by tabesin** [comment]
Note: this probably related to the debuild.sh script.
https://github.com/fossasia/meilix/blob/master/scripts/debuild.sh
As you can see this should be resolved.

We also have in chroot
```
rm meilix-default-settings_1.0_all.deb
rm meilix-metapackage_1.0-1_all.deb
rm systemlock_0.1-1_all.deb 
rm plymouth-theme-meilix-logo_1.0-1_all.deb 
rm plymouth-theme-meilix-text_1.0-1_all.deb
```

If we are in strict mode a removal of an nonexisting file may be an error. 

So make it
`[ -f blabla.deb] && rm blabla.deb`
or 
` [ -d directory ] && rm -R directory`
