### ISSUE TITLE
Cannot index string published at

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#331]
- Issue type: Bug report

### Short description

Travis log shows near the end:
`
jq: error (at <stdin>:4): Cannot index string with string "published_at"
`
### Environment
travis-ci

**Comment by abishekvashok** [comment]
Related to release_maintainer

**Comment by pranav1698** [comment]
@tabesin @abishekvashok if you see the latest builds, 
We do not get this error
But something like: `expr: non-integer argument`

**Comment by pranav1698** [comment]
We can close this one
