### ISSUE TITLE
The travis build is failing with exit code 1

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#346]
- Issue type: Bug report/Feature request 

- Bug report

### Short description

In the current build the travis build is failing and exiting with code 1

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 
Travis
### Steps to reproduce

1.  Check the latest build of travis in fossasia/meilix
2. 
3. 

### Actual behaviour

```[0K[31;1mThe command "./build.sh |& tee home/travis/log.txt" exited with 1.```

**Comment by tabesin** [comment]
I tried to export the log.txt together with the iso.
