### ISSUE TITLE
Move systemlock building to its repo

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#350]
The build of the systemlock package should happen on its own repository via travis. https://github.com/fossasia/meilix-systemlock

Then the legacy deb file and the directory should be removed from this repository.

**Comment by meets2tarun** [comment]
After removing, the script also needs to be changed in such a way that it should now install meilix system lock from its repo.

**Comment by tabesin** [comment]
Sure, everything analog Pravad's leadership for meilix-artwork. Step by step.

**Comment by rpotter12** [comment]
is this issue is active??
I want to work on it :)

**Comment by pranav1698** [comment]
@rpotter12 the issue is still open but I am already working on it 
I have opened a PR in the meilix-systemlock repo

**Comment by pranav1698** [comment]
https://github.com/fossasia/meilix-systemlock/pull/24
