### ISSUE TITLE
gksu build dependency for systemlock debian package has been removed from ubuntu bionic 18.04

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#352]
- Issue type: Bug report

### Short description

If you try to build the systemlock debian package, 
You will get this error: 
Unmet build dependencies: gksu

If you try to install gksu in  Ubuntu bionic 18.04 you will get this error:
Package gksu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'gksu' has no installation candidate

On searching this error on the internet, I found that: https://itsfoss.com/gksu-replacement-ubuntu/ 
It has been removed from the ubuntu

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 
 - Software source: 

### Steps to reproduce

1.  Try make the debian system package  
2.  You will get the unmet build dependencies error: gksu
3.  Installing gksu you will get no installation candidate error

### Expected behaviour

Build process should occur without any error

**Comment by pranav1698** [comment]
@meets2tarun @tabesin can we have any alternative for gksu

**Comment by meets2tarun** [comment]
@pranav1698 What about nautilus?

**Comment by pranav1698** [comment]
@meets2tarun I will check on that 
Could you please review https://github.com/fossasia/meilix-systemlock/pull/24 so that we can move this issue to systemlock repo

**Comment by pranav1698** [comment]
@meets2tarun nautilus-admin is the correct alternative for this issue

**Comment by tabesin** [comment]
lxqt-sudo
is the obvious choice.
