### ISSUE TITLE
Switching to cosmic

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#369]
- Issue type: Feature request 

### Short description

Switching the release for debootstrap from xenial to cosmic
I tested the cosmic release for meilix while working on bionic release, cosmic is much better than the cosmic release because of the issues mentioned in pr #362 
Making issues in the bionic release is solved in the cosmic version as mentioned in: https://forum.lxqt.org/t/how-install-lxqt-on-ubuntu-server-18-04-command-line/360/4

### Description

You can test the cosmic release here: https://github.com/pranav1698/meilix/releases/tag/untagged-93c66ce27e30c1852d0d

**Comment by tabesin** [comment]
Start by adding a sources.cosmic.list to the repo.
