### ISSUE TITLE
Skype not found

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#37]
Although skype metapackage is included in the root directory of meilix but it is not found while searching for skype in the OS.

**Comment by tabesin** [comment]
https://www.skype.com/en/download-skype/skype-for-linux/downloading/?type=weblinux-deb

Package was deleted by Canonical from Zesty / canonical partners repo.

**Comment by tabesin** [comment]
On the original issue #37 check the package cp command into the chroot.
