### ISSUE TITLE
Switching off power management features for meilix

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#389]
- Issue type: Feature request 

### Short description

Switching off power management features for meilix ISO as required in the meilix generator

### Usecase

The power management fetures should be turned off for meilix

**Comment by tabesin** [comment]
Please note that the solution previously found in default-settings may not be the correct one. 

The best approach is one script per feature. This "could" also mean one deb package per feature but no need to over-engineer.

In any case we need first a mechanism how to sent the "receipe" from the app to the build server. "receipe" = a bundle of build variables and download links. Or maybe where files are concerned (zip, wallpaer) they are sent/handed over as binary streams. Get back to Tarun and Harsh on this. 

Either it's sth like (pseudo coding ahead)

> feature1 = yes
> wallpaper_link = http://mydownload.com/meilix/ahsjajs.png

or 

> feature1 = 0
> wallpaper = "$§$%)$)!$)"$§"§.... binary blob ...324"

etc.

Implement the pipe for one, solve all of them. ;)

But: We have to do it in a way that the features are suffiiciently separated and clean. So ideally we have a shell script per feature in the way (pseudo code)

> if feature_1 then exec feature_1.sh
> 
> if feature_32bit then install 32 bit app else install 64bit app.

**Comment by pranav1698** [comment]
@tabesin thanks for the approach I will certainly look onto it
