### ISSUE TITLE
Releases are not working

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/meilix#39]
Github releases are not working because the API token has been changed in a recent PR, we need to get it back.

**Comment by Abhi2424shek** [comment]
That's the same reason for the Build failure also.

**Comment by meets2tarun** [comment]
Build is successful, I think deployment failure is coming.

**Comment by meets2tarun** [comment]
Should I make a P.R with the old secure key.

**Comment by Abhi2424shek** [comment]
Deployment fails the build, yes you can make a profit with the old token

**Comment by meets2tarun** [comment]
But it may leads that my forked repository will stop to build successfully.

**Comment by Abhi2424shek** [comment]
Please see my comment on your pr

**Comment by meets2tarun** [comment]
The last [comment](https://github.com/fossasia/meilix/pull/35)

**Comment by Abhi2424shek** [comment]
Yea
