### ISSUE TITLE
Add continuous integration tests and other frameworks

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix#4]
- [x] Enhance travis
- [x] Add codacy

**Comment by Abhi2424shek** [comment]
I got this down

**Comment by Abhi2424shek** [comment]
@mariobehling in travis we would have to run ./build.sh right

**Comment by mariobehling** [comment]
yes, correct. Please check if it works. There might be restrictions.

**Comment by Abhi2424shek** [comment]
@mariobehling we are running setup.py on travis that's why we fail, let me give out a new PR.

**Comment by Abhi2424shek** [comment]
@mariobehling please see #6 and for codeacy it's present already sir

**Comment by Abhi2424shek** [comment]
@mariobehling why did you open this sir?

**Comment by mariobehling** [comment]
It is not working. As you can see tests are failing.

**Comment by Abhi2424shek** [comment]
@mariobehling the tests failing because of PAM module error, `dpkg` when processing encountered an error, that error is what we have to fix and not to tweak Travis, can we have a separate issue for that :)

**Comment by mariobehling** [comment]
Thanks. Please open an issue.

**Comment by Abhi2424shek** [comment]
@mariobehling sure
