### ISSUE TITLE
Travis CI is taking a long time to compile the code

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#40]
The average build time is around 27mins or so, it would have been better if we could investigate faster CIs and move the build function to there and keep the Content Delivery with Travis (metapackage pushing to gh-pages). What are your thoughts?

**Comment by meets2tarun** [comment]
Yeah, it would be great to reduce the time. There are other CI in the market i.e; circleci, snap-ci, etc but travis is quite helpful and Github also recommends Travis. But if only time matterss, we can try a better one.

**Comment by niccokunzmann** [comment]
Is there a way to split the process: Separate meta packages from building the image?

**Comment by Abhi2424shek** [comment]
Yea you are right @niccokunzmann, we are also putting them into our apt source repository (gh-pages acts as an apt source repository)

**Comment by Abhi2424shek** [comment]
We can't separate the process as far as I can see.

**Comment by niccokunzmann** [comment]
@Abhi2424shek I see that [aptRepoUpdater.sh](https://github.com/fossasia/meilix/blob/master/scripts/aptRepoUpdater.sh) and [build.sh](https://github.com/fossasia/meilix/blob/master/build.sh) are two different scripts.

**Comment by niccokunzmann** [comment]
But now to the analysis: which steps are taking which time and what is taking it so long?

**Comment by Abhi2424shek** [comment]
Yep. But we can't split build.sh,h owever we can't be sure, I am investigating.... It would be best if you guys could also do the same :)

**Comment by Abhi2424shek** [comment]
Distributed computing can be applied, but I don't think Travis is supports it.

**Comment by abishekvashok** [comment]
Here are some findings: @niccokunzmann @meets2tarun @xeon-zolt 

- Seems like Travis has better download speeds when caches are in the S3 bucket in the us-east region.
- The apt updater script can be made to run parallel.
- Travis does things faster if we put things we need in the .travis.yml file [Don't change build.sh as if we run apt-get install again from there since, packages are present apt will skip downloading and say that they are upto date] like this

```
 include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - packagename-version
```

**Comment by meets2tarun** [comment]
@abishekvashok 
Thanks, you remind me again to look at the parallel build and thanks for the finding too.
I'm referring you and [this](https://docs.travis-ci.com/user/speeding-up-the-build/).

**Comment by meets2tarun** [comment]
@abishekvashok I parallel the build but it still takes the same time?
https://travis-ci.org/fossasia/meilix/builds/246607082

**Comment by abishekvashok** [comment]
It would make a small difference as the script won't take much time. But each second is valuable right?

**Comment by abishekvashok** [comment]
Its not yet solved. The sources are still fetched from build.sh please be careful.

**Comment by meets2tarun** [comment]
> The sources are still fetched from build.sh please be careful.

Please elaborate

**Comment by abishekvashok** [comment]
As i stated:

> Travis does things faster if we put things we need in the .travis.yml file [Don't change build.sh as if we run apt-get install again from there since, packages are present apt will skip downloading and say that they are upto date] like this
 include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - packagename-version

**Comment by abishekvashok** [comment]
any updates on this @meets2tarun

**Comment by meets2tarun** [comment]
Since we have shifted the build to generator branch from the master branch and generator branch uses a different strategy to build the ISO.
But on the other hand master branch uses the same old method to build and same time also.
I have doubt in this [approach](https://github.com/fossasia/meilix/issues/40#issuecomment-315377594), and I hope you to give a PR.

**Comment by abishekvashok** [comment]
@meets2tarun I get the logic now, but on the other hand, I have found some simple logical problems on to both branches which will be required. Opening issues for those.

> I hope you to give a PR

On the way.

**Comment by abishekvashok** [comment]
@tabesin i didnt solve it as yet. A commit to the master branch takes in 24mins to complete

**Comment by meets2tarun** [comment]
@abishekvashok 
If you're working on the issue then kindly open the issue and file a PR.
