### ISSUE TITLE
Executing the copied chromium-package script in the chroot environment 

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#419]
- Issue type: Feature request 

### Short description

After #418 is merged, the updated chromium package script needs to be executed in the chroot environment 
This will install the chromium web browser in the meilix custom ISO

**Comment by tabesin** [comment]
Alright we need the condition whether we take 64bit or 32bit installation.

**Comment by pranav1698** [comment]
@tabesin I will option a issue for the same
