### ISSUE TITLE
Why are TraivsCI logs so much verbose that debugging is a nightmare

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#427]
fix logs of Travis CI
will link mini issues to this one

#428 
#429 
#430 
#431 

other than this logs are so big that Travis says that its the limit you cannot read any further we need to remove all unnecessary ls and cat commands if the debugging for those parts are done I know they were added to do debugging but why no one cared to remove them once it was done we need to do cleanup 

> also, this is a request to other fellow maintainers that don't merge any pull request without proper testing and checking logs because I find things very messy inside Travis and it needs to be fixed

**Comment by xeon-zolt** [comment]
![build 1552 fossasia meilix travis ci 3](https://user-images.githubusercontent.com/4529442/53913604-be596800-4081-11e9-90ec-369b6055eb93.png)

job of a maintainer is a hell if he is downloading logs and then going through to see what the bug is it need to be FIXED

**Comment by pranav1698** [comment]
True enough!! @xeonxolt, @tabesin please review this issue, I suppose most of these verbose  logs were used by maintainers when meilix was not booting into a live ISO
Now they can be removed,

**Comment by xeon-zolt** [comment]
> True enough!! @xeonxolt, @tabesin please review this issue, I suppose most of these verbose logs were used by maintainers when meilix was not booting into a live ISO
> Now they can be removed,

@xeon-zolt it is

**Comment by tabesin** [comment]
Hi Xeon-Xolt. 

The full log you always get via "raw log", it is not feasible to get it in the Travis log display. Verbosity was on purpose to see what is going on an failing. If commands get a lower verbosity level, unless obvious cases, better use the long version of paramters except in obvious cases.

e.g. wget with -q means we may see when a download fails.

I think we should export the Log file together with the ISO file.

**Comment by xeon-zolt** [comment]
@tabesin then we can have verbose in a dev branch otherwise verbose is not required cat is taking too much of logs
