### ISSUE TITLE
why their is a cat present in logs ??

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#431]
we should remove that 
![build 1552 fossasia meilix travis ci 2](https://user-images.githubusercontent.com/4529442/53913272-f8763a00-4080-11e9-8c91-7a1b6b25e235.png)
its printing a huge file in logs

**Comment by alok760** [comment]
/scripts/meilix_check.sh (https://github.com/fossasia/meilix/blob/master/scripts/meilix_check.sh) contains all the cat, less, echo and ls shown in Travis logs
if meilix_check is not required I would like to work on this issue.

**Comment by xeon-zolt** [comment]
please remove them if required for debugging by someone it should be done on a fork not to mess up with master

**Comment by pranav1698** [comment]
@xeon-zolt @tabesin Most of the logs that are been produced by meilix-check script I think is of the time when meilix was not booting  into a live ISO,
Still we need your help, on deciding which commnd to delete and which to not

**Comment by pranav1698** [comment]
I will be opening a pr removing the commands that are producing unnecessarily long logs

**Comment by xeon-zolt** [comment]
@tabesin maybe we should stop calling check script for production system

**Comment by pranav1698** [comment]
@xeon-zolt the current meilix logs have less nuimber of cats and this issue can be closed
you can check this log: https://travis-ci.org/fossasia/meilix/builds/516150684

**Comment by tabesin** [comment]
@xeon-zolt That is the point. The check script should provide as much info as possible. However it does not need to be called by default.
