### ISSUE TITLE
Meilix-check script is called twice during the build

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#440]
- Issue type: Bug report 

### Short description

Currently the output of the meilix build is real noisy,
One of the reasons is the execution of meilix-check script being operated twice
Meilix check operates once when all the bash scripts copied in chroot is executed,
`chmod +x ./*.sh
./*.sh
`
Next in the end of the script:
`chmod +x meilix_check.sh
./meilix_check.sh`

**Comment by tabesin** [comment]
the purpose of the diagnosis script is to output as much info as possible. Of course it could be commented out at this stage.
