### ISSUE TITLE
Installing the 3rd Party Softwares sent from the webapp into the ISO

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#450]
- Issue type: Feature request 

### Short description

In the current build, recipe array is sent to the build server from the meilix-generator now as an environment variable of the build server, Next steps would be installing the sent packages(chosen by the user) into the Meilix ISO.
The user has the options to choose from a set of packages and then it needs to be installed into the ISO.

### Usecase

This feature will help to create custom distributions which will have the 3rd party softwares that needs to be pre-installed that to choosen by the user. The various options can be seen by seeing the meilix-generator.

**Comment by rpotter12** [comment]
#446 is also related to this issue

**Comment by pranav1698** [comment]
Yeah, it will cover all 3rd party softwares that can be installed in the system
