### ISSUE TITLE
Adding dummy scripts for disabling features in the meilix ISO 

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix#469]
- Issue type: Feature request 

### Short description

In the current codebase, the commands for disabling features in meilix by executing commands only in the `chroot_reconst` script.
As proposed by @tabesin in #464 we can have dummy scripts for disabling these features and this will also help in enabling these features using the meilix-generator easilly.
The following features needs refactoring:
- [ ] screensaver
- [ ] sleep modus
- [ ] screen dimming

### Usecase

Having dummy scripts for disabling features by default using the meilix ISO instead of executing them in the chroot-reconst script.

**Comment by tabesin** [comment]
The dummy factor is to have the scripts per feature before the actual feature gets added to the codebade.
