### ISSUE TITLE
Not able to build iso locally

### ISSUE THREAD

**Issue by hyPnOtiC-d00g** [fossasia/meilix#480]
- Issue type: Bug report

### Short description
Not able to build iso locally.

### Environment

 - Operating system: Zorin 15
 - Software source: Github Repository

### Steps to reproduce

1.  cd into the meilix folder.
2.  make build.sh executable.
3.  execute build.sh.
4. Returns the error as shown in the picture.

![5676197543936000_1578755817_Screenshot_from_2020-01-11_20-46-29](https://user-images.githubusercontent.com/44530973/72207932-2c9d6100-34c3-11ea-900b-a89377211bc9.png)

### Expected behaviour
 It should be able to build the iso.

### Actual behaviour
 won't build iso.

**Comment by xeon-zolt** [comment]
sorry, the script is not used for local builds but you can create a Pull request to code and set a flag for a local build like ./build.sh --local if you want to it can a 

<p 'I know you are noob and you cannot read this'>good first issue</p>

if you want to run it on local you need to export some env variables which are used for Travis or remove the condition on line 16 I would suggest by trying to export some random value in $TAVIS_TAG variable

**Comment by hyPnOtiC-d00g** [comment]
Removing the condition on line 16 didn't work

**Comment by hyPnOtiC-d00g** [comment]
Okay thanks, it worked. :)
