### ISSUE TITLE
Building of auto-generated webapp from readme

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#50]
The task is to auto-building of the webapp from the readme.
LIke [this](http://dev.loklak.org/server/)

**Comment by Abhi2424shek** [comment]
Should we need this now, i think we should do this later.

**Comment by meets2tarun** [comment]
The readme of meilix can be very large to make one understand it quite easily and to present it in a better way, I prefer this. Not today, but tomorrow we will feel its need, so why not do it today ?

**Comment by Abhi2424shek** [comment]
This is useful only by the time we split docs.

**Comment by meets2tarun** [comment]
Yeah, docs can be split by splitting content of 
- building/compiling of the distro
- customizing the distro
- customizing the metapackage
- building the metapackage
- adding the metapackage, etc

**Comment by Abhi2424shek** [comment]
IMO, the docs are not that much long as compared to other projects like the susi server. Should we do this now @mariobehling?

**Comment by meets2tarun** [comment]
I think we should drop this idea for now?
