### ISSUE TITLE
Update the sources.list in chroot directory

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#51]
Chroot folder contains sources.list file which needs to be updated to zesty.
The user that locks a file or directory is the only one that can edit and push their changes back to the repository where the locked objects are located.

**Comment by tabesin** [comment]
guess this has been fixed and could  be closed now.

**Comment by meets2tarun** [comment]
No, this is not fixed yet.

**Comment by tabesin** [comment]
Ok, so, we need the Chrome repo and the LXQT repo -- what else?

**Comment by meets2tarun** [comment]
Till now this much.

**Comment by tabesin** [comment]
Plus the key for the custom repos need to be added. There is a key section in build.sh
