### ISSUE TITLE
Build failing because my access token has no rights

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix#53]
Seems like my access from the repo has vanished somehow and I can't write to it, as a coincidence the build is also failing because my personal token was used for pushing out releases.

_NB: I also lost access from some other repos where I could merge PRs also, and I think i haven't done anything with my acc or experimented anything in the near past, so I am confused of how my accesses have been lost :(_

**Comment by niccokunzmann** [comment]
I was added today to the meilix group of fossasia. I think, the administrators changed who has access. I have write access. I believe, this will change again. It expect that you can be added again in the near future. 
I do not know who revoked access. You could have a look at the teams to see who has rights for the repository https://github.com/orgs/fossasia/teams

**Comment by Abhi2424shek** [comment]
@niccokunzmann oh, seems i am out, no worries :) please generate a access token and add it to the repository since you got push access.

**Comment by meets2tarun** [comment]
Shall we rectify this deploying error soon?

**Comment by Abhi2424shek** [comment]
@niccokunzmann or @mariobehling will someone of you handle over your access tokens or add it yourself so that the build will not fail and will pass giving us regular releases to test. Another maybe unsuitable option would be to give me push access. Please do any of the mentioned ones.

Thankyou.

**Comment by niccokunzmann** [comment]
I do not know if this is the token as 404 is the error code. https://travis-ci.org/fossasia/meilix/builds/229473165#L8628

**Comment by niccokunzmann** [comment]
@meets2tarun Do you have push access now? If yes, you can provide your token.

**Comment by meets2tarun** [comment]
No, I don't have push and merge access.

**Comment by abishekvashok** [comment]
@niccokunzmann pls provide a token

**Comment by meets2tarun** [comment]
@abishekvashok I can also provide; if everyone agrees.

**Comment by abishekvashok** [comment]
@meets2tarun do you have push access? If so pls do so.

**Comment by meets2tarun** [comment]
@abishekvashok  Sorry, I don't have.
But my forked repo is building successfully, so if I get the access, then can use my token.

**Comment by meets2tarun** [comment]
My token is working in meets2tarun/meilix and I can provide also my token.
Should I go for it?

**Comment by abishekvashok** [comment]
If you have push access

**Comment by niccokunzmann** [comment]
#61 fixes this

**Comment by abishekvashok** [comment]
Still failing @niccokunzmann

**Comment by meets2tarun** [comment]
@abishekvashok @niccokunzmann

**Comment by abishekvashok** [comment]
> 401 - Bad credentials Unauthorised

That's a permission error.

**Comment by meets2tarun** [comment]
> That's a permission error.

I even have the push access to the repo and even use it in setting to define the environment variable in Travis, then why it is showing such error?

**Comment by niccokunzmann** [comment]
I think, a travis encrypt only works for one repository.
If the token works for your repository, it may not work for fossasia.

**Comment by meets2tarun** [comment]
Should I use a different token from my GitHub personal access token?
that may work.

**Comment by niccokunzmann** [comment]
You can use the same token but you must encrypt it again for meilix.
The same token will have a different "secure: ..." string

**Comment by abishekvashok** [comment]
> I think, a travis encrypt only works for one repository.

Yes.

> Should I use a different token from my GitHub personal access token?

No need, but you should encrypt it again when you are on this repo or you should specify the repo name explicitly as an argument.

**Comment by meets2tarun** [comment]
Thank you, everyone
I encrypt the same key for fossasaia/meilix repo.
https://github.com/fossasia/meilix/commit/3be7bad4528a40625fea75cceb742eaa4948105e
Closing now, issues resolved.
