### ISSUE TITLE
.json or config file for firefox

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#60]
Similar to chromium, where is the .config or .json file for the firefox browser to edit the preference of the browser?
Is there any way for the configuration?
@Abhi2424shek @xeon-zolt

**Comment by niccokunzmann** [comment]
https://github.com/CoderDojoPotsdam/software/blob/master/linux-update/set_startup_homepage.sh / this is how I set the startup homepage.

**Comment by meets2tarun** [comment]
@niccokunzmann  In Firefox, you can only configure that homepage.
And had you done this config in the prefs.js file?

**Comment by abishekvashok** [comment]
@meets2tarun i guess that's the only way.

**Comment by meets2tarun** [comment]
>https://github.com/CoderDojoPotsdam/software/blob/master/linux-update/set_startup_homepage.sh / this is how I set the startup homepage.

@niccokunzmann 
How can I use this file to config my firefox?

**Comment by niccokunzmann** [comment]
It is a shell script which can be executed. 

You can read more about it here: http://askubuntu.com/questions/73474/how-to-install-firefox-addon-from-command-line-in-scripts

**Comment by meets2tarun** [comment]
And what to do if I want to do other configs too?

**Comment by niccokunzmann** [comment]
I do not instruct you to do anything. I do not want you to do anything in a special way. I just wanted to give you a starting point or a hint on where to look. Please find it out yourself. If you have a question on how to do something, please provide the context of your research, what you tried and what did not work out. If you do that, your question might also be answered on stackoverflow/stackexchange.

**Comment by meets2tarun** [comment]
Sure, the thing I left with is and my question was something as but I hadn't elaborated that much:
`user_pref("browser.startup.homepage", "https://google.com");`
this is the function one can put in prefs.js to get the required homepage in Firefox, I was asking that this is a defined function and there must be other functions too for the rest of the configuration, which one can use to come with their required need like the bookmark, reopen last tabs, etc, so I started to search that is there such function also exists or how can one make it of its own?
http://kb.mozillazine.org/Editing_configuration
Anyway @niccokunzmann you always help me to get on the right path.
Thanks.

**Comment by tabesin** [comment]
Could this ticket be set closed?
