### ISSUE TITLE
Process to get configuration

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix#62]
The webapp should configure the meilix build.

When Travis builds, the environment is [configured](https://github.com/fossasia/meilix-generator/pull/18/files#diff-8e6afdf322bc86524af61ffc82e64ca3R13).
This environment can contain a variable, e.g. `CONFIGURATION_SCRIPT_URL`.
This url should point to a script which can be downloaded, e.g.
`CONFIGURATION_SCRIPT_URL=https://meilix-generator-test.herokuapp.com/configurations/TAG_NAME.sh`

The travis build looks for such a variable. If it is present, it downloads the file and marks it as executable.
In the `chroot` of meilix, the file is executed.

This approach does the following:
- it is extensibe: Different web apps can use different configurations
- if is fast to make it work
- It can be changed later to bootstrap different types of configurations, e.g. a json configuration

Related:
- The meeting https://pad.freifunk.net/p/hangout-01

**Comment by meets2tarun** [comment]
What I understand is:
There is an environment variable `CONFIGURATION_SCRIPT_URL` in a script named `TAG_NAME.sh`.
The Travis build tries to find the variable and if found it downloads the `TAG_NAME.sh` and run it.
`TAG_NAME.sh` contains configuration which is applied overriding any other configuration.

Please correct me if I'm wrong.

**Comment by niccokunzmann** [comment]
Your formulation is compatible with mine. So, yes, I think, you understand.

**Comment by meets2tarun** [comment]
I have a thought:
Suppose we have to make changes in the configuration of meilix, then we will edit the conf file or json file or the .skel one depending upon the respective changes.
Now the idea is that we will make changes in the required file but not by editing it directly but editing the same using webapp through Heroku then download the script (as suggested by @xeon-zolt ) as same as we are doing for wallpaper till now, and then run the build script and get the required iso.

@xeon-zolt Please elaborate and reflect your idea.

**Comment by tabesin** [comment]
Very nice item about showing the entrance to the rabbit hole but no current "issue".

**Comment by abishekvashok** [comment]
@tabesin we could have added the `later` label
