### ISSUE TITLE
To make a new branch

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#63]
We are using Travis to trigger the build of meilix but now in a forked repo [here](https://github.com/fossasia/meilix-generator/blob/master/travis_tokens) since we made required changes in our master branch. 
The idea is to make a new branch as `generator` which will contain the required changes.
@mariobehling @niccokunzmann  Help us in this matter.

**Comment by niccokunzmann** [comment]
https://github.com/fossasia/meilix/tree/generator The branch is created.

**Comment by xeon-zolt** [comment]
closing the issue as the branch is created
