### ISSUE TITLE
Shorten the Build time for meilix generator by using mkiso

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#74]
### Short description

by using mksio and squash tools instead of rebuilding whole iso which takes time we can create changes in iso and repack it

**Comment by xeon-zolt** [comment]
@meets2tarun  can you please check why I am having Travis error in my pull request but it is not showing error here https://travis-ci.org/xeon-zolt/meilix

**Comment by abishekvashok** [comment]
Remember that will make work to clone the repository awfully, as git doesnot have diff support for .iso files. Its not a good idea to store the .iso.

**Comment by abishekvashok** [comment]
And if you download the iso in Travis, it will be really slow as you as Travis has a slow download speed.

**Comment by xeon-zolt** [comment]
@abishekvashok faster than  building from sources 8 minutes compared to 20

**Comment by abishekvashok** [comment]
@xeon-zolt if so, Travis has better download speeds when caches are in the S3 bucket in the us-east region.

**Comment by meets2tarun** [comment]
#75 solves this? @xeon-zolt 
Please paste a screenshot or link to Travis building in support before closing this.

**Comment by xeon-zolt** [comment]
https://travis-ci.org/fossasia/meilix/builds/254818077
