### ISSUE TITLE
Repository Clean Up

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#76]
The generator branch is made for the webapp basically. So we need to clean up the branch to make it suitable for customization.
The cleanup include: meilix-default-settings/debian/changelog should be edited to version 1.0

**Comment by xeon-zolt** [comment]
now it is mainly mkiso script so it's better to clean everything from generator branch to save time wasted in cloning it in travis

**Comment by tabesin** [comment]
With #89 merged could that ticket be closed?
