### ISSUE TITLE
Zesty version doesn't boot directly into GUI

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#79]
There is an issue with the zesty that it doesn't boot directly into the GUI rather it boots into CLI.
And since meilix is going to use for the event like purpose, I think it's better to rely on LTS version and roll-back to xenial (16.04).
@mariobehling @niccokunzmann @abishekvashok @xeon-zolt

**Comment by meets2tarun** [comment]
If we get back to xenial, then there would be nay further issue, and we'll start to work on the LXQt community version of meilix. But if we care about zesty, then that can cause problems with the dependencies and many other issues also and Awk has also been released.

**Comment by tabesin** [comment]
Xenial does not support lxqt out of the box, zesty will

**Comment by tabesin** [comment]
Maybe tarun, just take 3 days, install zesty on a virtualbox and build lxqt packages from source. If you can get it run on a local virtual machine,  your packages will work in meilix, too.

**Comment by tabesin** [comment]
All ubuntu flavours come as desktop and headless. As we take lxqt it does not matter.

**Comment by meets2tarun** [comment]
> Xenial does not support lxqt out of the box, zesty will

No, I have tried LXQt on xenial also. And I think there are lots of advantages to going for LTS version.

**Comment by meets2tarun** [comment]
@mariobehling Please clear the issue here as it is delaying the speed of the progress of the project.

**Comment by tabesin** [comment]
1. Have you got LXQT run on a local install, whatever the base? Have you made custom packages?

2. For a decision you have to specify which "advantages" or "blockers". Otherwise the change request is not useful.

3. An underspecified decision on 2 should not block activities. E.g. on item 1.

**Comment by meets2tarun** [comment]
>Have you got LXQT run on a local install, whatever the base? Have you made custom packages?

Yes, on xenial Ubuntu in VM.

>For a decision you have to specify which "advantages" or "blockers". Otherwise, the change request is not useful.

The advantages for going to xenial are:
This is an LTS which almost support all the packages.
Metapackages are already build for the xenial but it hasn't been build for yak nor for zesty.
Now if you think we can update meilix to awk but it really doesn't mean anything unless until some benefits come out of it. We love updates but the stable one. It, not that update number matters which looks good when it gets increased but the point which matters is that we would be able to run everything which is able to run in the previous version.

**Comment by tabesin** [comment]
a) Ok. You have LXQT run on Xenial. Which git checkout? Have you build Xenial packages for LXQt?
What were your steps. feel free to document your steps in a text file in GIT

b) LTS / "almost all packages" seems irrelevant in this generic notion. LTS are not stable but long term support.

Have you tried the same using zesty?

**Comment by meets2tarun** [comment]
When an update in the source has been done then one of the processes for a successful update is: rebuilding every metapackages for the update.
Since @vanhonit can help us to update the metapackages that don't have .change file or the one which has .change file @abishekvashok that I don't know how to do it?
https://github.com/fossasia/meilix/issues/25

**Comment by meets2tarun** [comment]
And https://github.com/fossasia/meilix/blob/untagged-c9f68d2fa6b3d1cdbd99/build.sh#L140
is also there which is responsible for the GUI but still, it loads into CLI.

**Comment by tabesin** [comment]
Your metapackage files do not include GUI components, so it does not get installed.

You also have to add the repositories to Julian's scripts from which to fetch the GUI packages.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/pull/84
Solves this
