### ISSUE TITLE
Repository for distro

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix#8]
The goal is to keep our files on our own server and have our own repository. What is the simplest model to get this for now?

**Comment by mariobehling** [comment]
Here is a project that I found, which could be used: https://github.com/krobertson/deb-s3

**Comment by mariobehling** [comment]
Or: Turn your Apt repo into a git repo http://www.hackgnar.com/2016/01/creating-remote-apt-package.html

**Comment by mariobehling** [comment]
Another starting point: https://www.reddit.com/r/jailbreak/comments/3cc4fn/tutorial_how_to_set_up_a_repo_using_github_pages/

**Comment by Abhi2424shek** [comment]
I got the solution sir @mariobehling we could easily set up one apt repository; We could run a script with Travis that pushes to a git repo hosted on the server and make a copy and convert it to a apt repository;

But can you @mariobehling have a server for it or should i afford the server, a domain name is also required as we cant host it on github. Sub domains are accepted by apt, so we would require a web server to host the packages what is your view sir @mariobehling

**Comment by Abhi2424shek** [comment]
@mariobehling done it see PR #8

**Comment by mariobehling** [comment]
@Abhi2424shek Preferred solution would be to use GitHub pages. See earlier my [comment](https://github.com/fossasia/meilix/issues/8#issuecomment-269116760). We can define a subdomain for this e.g. apt.fossasia.org.

**Comment by Abhi2424shek** [comment]
@mnariobehling would follow it up, I saw it the comment states apt to git but it should be git to apt!

**Comment by Abhi2424shek** [comment]
@mariobehling please see PR #10 it resolves this issue

**Comment by Abhi2424shek** [comment]
@mariobehling why did you open it sir?

**Comment by Abhi2424shek** [comment]
@mariobehling why was it opened sir?

**Comment by yukiisbored** [comment]
For the time being, we can just use launchpad.net as the hosting platform and manager of the repository. The reason why I picked launchpad.net is because it's easy to use and get started. We can do an advanced "real" repository later.

**Comment by Abhi2424shek** [comment]
Hey @yukiisbored, we had a discussion and I too recommended to host on launchpad but we want the sources on our own server hence came to the conclusion to use this repo's gh-pages branch for the repository. Currently my PR #14 initializes the branch and the PR #15 creates a script which updates the sources when a new metapackage added PR is merged! The PR #14 did a lot of deletions and the branch wasn't enabled so after enabling the branch it took some time to finish. So that's why it was not merged as @mariobehling is the one one who presses the green button after reviewing.

Hence, after that PR is merged too we will have our own repository which will host our metapackages!

**Comment by yukiisbored** [comment]
I was wondering, isn't better if we leave Debian? Debian has a pretty complicated way of package management, repository, etc and it's too much to handle for a small community. Especially when the fact we don't even have our own server to host these repositories properly. `git` is pretty terrible at managing binary files (which is also the reason why this repo is pretty large), so I don't recommend setting up a repository with git. I was thinking it's better if we're using something like `ports` and the git repo is just filled with build/package scripts of various programs (like https://github.com/voidlinux/void-packages and https://github.com/6c37/crux-ports-git) and we can have a CI (probably Travis) that builds and deploys these `ports` into binary packages that the user can just install and download. It still uses `git` and `github` but we don't need to build it manually and pushing-pulling a large `git` repo.

**Comment by Abhi2424shek** [comment]
It's fixed already then why should we have this?
