### ISSUE TITLE
Blending of meilix with SUSI.Al 

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#81]
> Cooperate with the SUSI.AI hardware project to offer a dedicated Kiosk Meilix version with SUSI.AI for Raspis and Magic Mirror

@mariobehling, we went through your feedback and now in need of your help to understand the terms to start working on this.

**Comment by xeon-zolt** [comment]
Meilix for pi that means we need to compile it for arm based architecture
so if we have to do it for pi we need a issue to make build scripts for armv7 too

**Comment by xeon-zolt** [comment]
@meets2tarun can you test this code on meilix ISO
```
sudo apt install python3
sudo apt install python3-pip
sudo apt install flite
sudo apt-get install portaudio19-dev
sudo pip3 install pyaudio
git clone https://github.com/fossasia/susi_hardware.git
cd susi_hardware/app
./install.sh
python3 main.py #say SUSI
```

**Comment by meets2tarun** [comment]
![screenshot_lasst_2017-07-21_18 30 22](https://user-images.githubusercontent.com/15213246/28464422-c04b85d4-6e42-11e7-833d-b1f17097dd1f.png)

**Comment by xeon-zolt** [comment]
rerun the script after installing `swig`
`sudo apt install swig`

**Comment by meets2tarun** [comment]
We need two more packages
`libpulse-dev` and `swig`

**Comment by abishekvashok** [comment]
> so if we have to do it for pi we need a issue to make build scripts for armv7 too
Can we let user decide the architecture

**Comment by abishekvashok** [comment]
Plus, adding an interface for SUSI like a command which intiates a build of the ISO and a subsequent notification would be awesome, what do you think @mariobehling @meets2tarun @xeon-zolt .

**Comment by betterclever** [comment]
@abishekvashok I think that is not our use case. Our aim is to add SUSI to Meilix and not build an ISO using SUSI skill. Something like building iso is better a continuous integration process and we can do it in Travis CI. Why would we call SUSI to initiate that? It won't be needed frequently even if somewhat relevant.

**Comment by abishekvashok** [comment]
@betterclever it will be like an other interface for the meilix-generator.

**Comment by tabesin** [comment]
Guys, of course you need ARM packages for an ARM architecture. But it does not matter whether you get it work on i386 or ARM first. So when you start to think about ARM porting you take the second step first. The first step is getting it on Meilix which is i386 right now. 

A bit over the top is the issue whether SUSI could be used to trigger MEILIX builds, that is too much "eating your own dogfood".

**Comment by abishekvashok** [comment]
> A bit over the top is the issue whether SUSI could be used to trigger MEILIX builds, that is too much "eating your own dogfood".

No, it ain't. @tabesin.
